//----------------------------------------------------------------------------------------------------------
/*
 <pre>
 Copyright      Copyright ABB, 2006.
                All rights reserved. Reproduction, modification,
                use or disclosure to third parties without express
                authority is forbidden.

 System         Generic
 Module         Diagnosis Subsystem
 Description    Define the input table and fast output table default values
 Remarks        This file shall be generated by code generator
 </pre>
*/
//----------------------------------------------------------------------------------------------------------
#ifndef _DIAGNOSIS_TABLE_DEFAULT_H__

#ifndef __SUBSYSTEM_IDX_H__
  #error subsystem_idx.h must be included
#endif

#ifndef __DIAGNOSIS_TYPES_H__
  #error Diagnosis_types.h must be included
#endif

#ifndef __DIAGNOSIS_IDX_H__
  #error diagnosis_idx.h must be included
#endif

#ifdef _DIAGNOSIS_TABLE_DEFAULT_H__
  #error diagnosis_table_default.h included more than once
#endif

#define _DIAGNOSIS_TABLE_DEFAULT_H__

//----------------------------------------------------------------------------------------------------------
//! Input Table
//@CodeGen start@ <INPUT_TABLE>
#define INPUT_TABLE_SIZE 48
extern const T_DIAGNOSIS_INPUT_TABLE inputTable[INPUT_TABLE_SIZE];
//@CodeGen end@ <INPUT_TABLE>

//----------------------------------------------------------------------------------------------------------
//! Fast Output Table
//@CodeGen start@ <FAST_OUTPUT_TABLE>
#ifdef DIAGNOSIS_USE_CONFIGURABLE_BEHAVIOUR
#define FASTOUTPUT_TABLE_SIZE 9
extern const T_DIAGNOSIS_FASTOUTPUT_TABLE FASTOutputTable[FASTOUTPUT_TABLE_SIZE];
extern const T_DIAGNOSIS_TABLE_ADDRESSING FASTOutputTableAddressing[MEMBER_IDX_NUM_ELEMENTS];
#endif
//@CodeGen end@ <FAST_OUTPUT_TABLE>

//----------------------------------------------------------------------------------------------------------
//! Simulation Data
//@CodeGen start@ <SIMULATION OBJECTS>
#define LAST_SIMULATION_OBJECT DIAGNOSIS_IDX_totalizerAlarmSimulation
#define FIRST_SIMULATION_OBJECT DIAGNOSIS_IDX_analoginputAlarmSimulation
//@CodeGen end@ <SIMULATION OBJECTS>

#define SIMULATION_OBJ_TABLE_SIZE ((LAST_SIMULATION_OBJECT - FIRST_SIMULATION_OBJECT) + 1)

//lint -e{641} Giovanni Invernizzi 2007-06-26 Converting enum to int accepted
//lint -e{656} Giovanni Invernizzi 2007-06-26 Arithmetic operation uses (compatible) enum's accepted
extern const T_DIAGNOSIS_SIMULATION_OBJ_ADDRESSING simulationObjTable[SIMULATION_OBJ_TABLE_SIZE];
//lint -e{641} Spring 2013-05-23 Converting enum to int accepted
//lint -e{656} Spring 2013-05-23 Arithmetic operation uses (compatible) enum's accepted
extern const T_DIAGNOSIS_SIMULATION_MAPPER DiagnosisSimulationTable[SIMULATION_OBJ_TABLE_SIZE];
#endif



