//----------------------------------------------------------------------------------------------------------
/*
 <pre>
 Copyright      Copyright ABB, 2006.
                All rights reserved. Reproduction, modification,
                use or disclosure to third parties without express
                authority is forbidden.

 System         Generic
 Module         Diagnosis Subsystem
 Description    Define the input table and fast output table default values
 Remarks        This file shall be generated by code generator
 </pre>
*/
//----------------------------------------------------------------------------------------------------------
#include <stdio.h>

#include "System/Interface/system.h"
#include "System/Interface/common_type.h"
#include "RTOS/Interface/rtos.h"
#include "T_DATA_OBJ/Interface/simple_type.h"
#include "T_DATA_OBJ/Interface/t_data_obj.h"
#include "T_Unit/Interface/t_unit.h"
#include "Coordinator/Interface/subsystem_idx.h"

#include "Diagnosis/interface/DiagnosisCompileTimeDefinitions.h"
#include "Diagnosis/interface/t_data_obj_alarm.h"
#include "Diagnosis/interface/t_data_obj_alarm_counter.h"
#include "Diagnosis/interface/Diagnosis_idx.h"
#include "Diagnosis/interface/diagnosis.h"
#include "diagnosis_types.h"
#include "diagnosis_table_default.h"
#include "diagnosis_attributes.h"

//@CodeGen start@ <INCLUDE>
#include "AnalogInput/Interface/AnalogInput.h"
#include "AnalogInput/Interface/AnalogInput_idx.h"
#include "Coordinator/Interface/Coordinator.h"
#include "Coordinator/Interface/Coordinator_idx.h"
#include "DigitalOutput/Interface/DigitalOutput.h"
#include "DigitalOutput/Interface/DigitalOutput_idx.h"
#include "ElettronicServices/Interface/ElettronicServices.h"
#include "ElettronicServices/Interface/ElettronicServices_idx.h"
#include "FrontEndInterface/Interface/FrontEndInterface.h"
#include "FrontEndInterface/Interface/FrontEndInterface_idx.h"
#include "Mapper/Interface/Mapper.h"
#include "Mapper/Interface/Mapper_idx.h"
#include "MVMeasurement/Interface/MVMeasurement.h"
#include "MVMeasurement/Interface/MVMeasurement_idx.h"
#include "SVMeasurement/Interface/SVMeasurement.h"
#include "SVMeasurement/Interface/SVMeasurement_idx.h"
#include "Totalizer/Interface/Totalizer.h"
#include "Totalizer/Interface/Totalizer_idx.h"
//@CodeGen end@ <INCLUDE>
//----------------------------------------------------------------------------------------------------------
//! Input Table
//lint -e{641}
//@CodeGen start@ <INPUT_TABLE>
const T_DIAGNOSIS_INPUT_TABLE inputTable[INPUT_TABLE_SIZE] = {
    {FE_IDX,
    diagnosisDynamic.frontendinterfaceAlarm,
    FE_BOARD_COMM_ERROR,
    215,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fe_board_comm_error,
    DIAGNOSIS_GROUP_HW_STATUS_ELECTRONICS,
    DIAGNOSIS_CONDITION_FE_BOARD_COMM_ERROR,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fe_board_comm_errorDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_SYNC_MISSING,
    214,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fe_board_not_detected,
    DIAGNOSIS_GROUP_HW_STATUS_ELECTRONICS,
    DIAGNOSIS_CONDITION_FE_BOARD_NOT_DETECTED,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fe_board_not_detectedDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VORTEX_SENSOR_CIRCUIT_FAILURE,
    213,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_PV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VORTEX_SENSOR_OPEN,
    213,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_PV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VORTEX_SENSOR_SHORT,
    213,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_PV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VORTEX_SENSOR_DRIFT,
    213,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_PV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_TEMP_SENSOR_UPPER_LIMIT,
    212,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_sv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_SV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_sv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_TEMP_SENSOR_LOWER_LIMIT,
    212,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_sv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_SV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_sv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VIBRAT_SENSOR_CIRCUIT_FAILURE,
    211,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_tv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_TV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_tv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VIBRAT_SENSOR_OPEN,
    211,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_tv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_TV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_tv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VIBRAT_SENSOR_SHORT,
    211,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_tv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_TV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_tv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_VIBRAT_SENSOR_DRIFT,
    211,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_tv_sensor_failure,
    DIAGNOSIS_GROUP_HW_STATUS_SENSOR,
    DIAGNOSIS_CONDITION_TV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_tv_sensor_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_SNR_FAILURE,
    210,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fe_board_failure,
    DIAGNOSIS_GROUP_HW_STATUS_ELECTRONICS,
    DIAGNOSIS_CONDITION_FE_BOARD_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fe_board_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_FE_NV_FAILURE,
    209,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fe_nv_failure,
    DIAGNOSIS_GROUP_HW_STATUS_ELECTRONICS,
    DIAGNOSIS_CONDITION_FE_NV_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fe_nv_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_FE_RAM_FAILURE,
    208,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fe_ram_failure,
    DIAGNOSIS_GROUP_HW_STATUS_ELECTRONICS,
    DIAGNOSIS_CONDITION_FE_RAM_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fe_ram_failureDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_CB_NV_ERROR,
    207,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_cb_nv_failure,
    DIAGNOSIS_GROUP_HW_STATUS_ELECTRONICS,
    DIAGNOSIS_CONDITION_CB_NV_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_cb_nv_failureDetails},

    {AI_IDX,
    diagnosisDynamic.analoginputAlarm,
    AI_ALM_SPICOM_FAIL,
    202,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_cb_nv_warning,
    DIAGNOSIS_GROUP_CONFIG_STATUS,
    DIAGNOSIS_CONDITION_CB_NV_WARNING,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_cb_nv_warningDetails},

    {TOTALIZER_IDX,
    diagnosisDynamic.totalizerAlarm,
    TOTALIZER_STOP_ALARM,
    155,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_tot_counter_stop,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_TOT_COUNTER_STOP,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_tot_counter_stopDetails},

    {MAPPER_IDX,
    diagnosisDynamic.mapperAlarm,
    MAPPER_ALM_NO_HART_BURST_IN,
    153,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_no_hart_burst_in,
    DIAGNOSIS_GROUP_CONFIG_STATUS,
    DIAGNOSIS_CONDITION_NO_HART_BURST_IN,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_no_hart_burst_inDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_CB_ALARM,
    152,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_alarm_simu_warning,
    DIAGNOSIS_GROUP_CONFIG_STATUS,
    DIAGNOSIS_CONDITION_ALARM_SIMU_WARNING,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_alarm_simu_warningDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_CB_SIMUDATA,
    151,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_data_simu_warning,
    DIAGNOSIS_GROUP_CONFIG_STATUS,
    DIAGNOSIS_CONDITION_DATA_SIMU_WARNING,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_data_simu_warningDetails},

    {MVM_IDX,
    diagnosisDynamic.mvmeasurementAlarm,
    MVM_ALM_STEAM_STATUS_MISMATCH,
    116,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_steam_type_mismatch,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_STEAM_TYPE_MISMATCH,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_steam_type_mismatchDetails},

    {MVM_IDX,
    diagnosisDynamic.mvmeasurementAlarm,
    MVM_ALM_FLOWRATE_GT_103,
    115,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_process_flowrate_more_than_103,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_PROCESS_FLOWRATE_MORE_THAN_103,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_process_flowrate_more_than_103Details},

    {SVM_IDX,
    diagnosisDynamic.svmeasurementAlarm,
    SVM_ALM_FLOWRATE_GT_103,
    115,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_process_flowrate_more_than_103,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_PROCESS_FLOWRATE_MORE_THAN_103,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_process_flowrate_more_than_103Details},

    {MVM_IDX,
    diagnosisDynamic.mvmeasurementAlarm,
    MVM_ALM_FLOWRATE_REACH_QMAX,
    114,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_out_lims,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_PV_SENSOR_OUT_LIMS,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_out_limsDetails},

    {SVM_IDX,
    diagnosisDynamic.svmeasurementAlarm,
    SVM_ALM_FLOWRATE_REACH_QMAX,
    114,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_out_lims,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_PV_SENSOR_OUT_LIMS,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_out_limsDetails},

    {MVM_IDX,
    diagnosisDynamic.mvmeasurementAlarm,
    MVM_ALM_FLOWRATE_REACH_QMIN,
    113,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_out_range,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_PV_SENSOR_OUT_RANGE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_out_rangeDetails},

    {SVM_IDX,
    diagnosisDynamic.svmeasurementAlarm,
    SVM_ALM_FLOWRATE_REACH_QMIN,
    113,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_pv_sensor_out_range,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_PV_SENSOR_OUT_RANGE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_pv_sensor_out_rangeDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALRAM_T_MAX,
    112,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_sv_sensor_out_lims,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_SV_SENSOR_OUT_LIMS,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_sv_sensor_out_limsDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALRAM_T_MIN,
    111,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_sv_sensor_out_range,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_SV_SENSOR_OUT_RANGE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_sv_sensor_out_rangeDetails},

    {MVM_IDX,
    diagnosisDynamic.mvmeasurementAlarm,
    MVM_ALM_LOW_Q_VALUE_CUTOFF,
    110,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_low_flowrate_cutoff,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_LOW_FLOWRATE_CUTOFF,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_low_flowrate_cutoffDetails},

    {SVM_IDX,
    diagnosisDynamic.svmeasurementAlarm,
    SVM_ALM_LOW_FLOWRATE_CUTOFF,
    110,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_low_flowrate_cutoff,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_LOW_FLOWRATE_CUTOFF,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_low_flowrate_cutoffDetails},

    {SVM_IDX,
    diagnosisDynamic.svmeasurementAlarm,
    SVM_ALM_RE_OUT_LINEAR_RANGE,
    109,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_nv_concistency_check,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_NV_CONCISTENCY_CHECK,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_nv_concistency_checkDetails},

    {AI_IDX,
    diagnosisDynamic.analoginputAlarm,
    AI_ALM_CUT_OFF,
    107,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_tv_sensor_out_lims,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_TV_SENSOR_OUT_LIMS,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_tv_sensor_out_limsDetails},

    {AI_IDX,
    diagnosisDynamic.analoginputAlarm,
    AI_ALM_OUT_OF_RANGE,
    106,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fv_sensor_failure,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_FV_SENSOR_FAILURE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fv_sensor_failureDetails},

    {ELETTRONICSERVICES_IDX,
    diagnosisDynamic.elettronicservicesAlarm,
    ELETTRONICSERVICES_ALARM_AMBIENT_TEMP_TOO_HIGH,
    105,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_ambient_temp_reach_tmax,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_AMBIENT_TEMP_REACH_TMAX,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_ambient_temp_reach_tmaxDetails},

    {ELETTRONICSERVICES_IDX,
    diagnosisDynamic.elettronicservicesAlarm,
    ELETTRONICSERVICES_ALARM_AMBIENT_TEMP_TOO_LOW,
    104,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_ambient_temp_reach_tmin,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_AMBIENT_TEMP_REACH_TMIN,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_ambient_temp_reach_tminDetails},

    {DIGITALOUTPUT_IDX,
    diagnosisDynamic.digitaloutputAlarm,
    DIGITALOUTPUT_PULSENUMMAXALARM,
    103,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_nv_storage_active,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_NV_STORAGE_ACTIVE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_nv_storage_activeDetails},

    {MAPPER_IDX,
    diagnosisDynamic.mapperAlarm,
    MAPPER_ALM_PRESSURE_REACH_MAX,
    102,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fv_sensor_out_lims,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_FV_SENSOR_OUT_LIMS,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fv_sensor_out_limsDetails},

    {MAPPER_IDX,
    diagnosisDynamic.mapperAlarm,
    MAPPER_ALM_PRESSURE_REACH_MIN,
    101,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fv_sensor_out_range,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_FV_SENSOR_OUT_RANGE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fv_sensor_out_rangeDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_REPLACE_FE_TO_CB_BLOCKED,
    54,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_nv_replace_warn,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_NV_REPLACE_WARN,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_nv_replace_warnDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_REPLACE_REQUIRED_FE_TO_CB_BLOCKED,
    54,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_nv_replace_warn,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_NV_REPLACE_WARN,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_nv_replace_warnDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_REPLACE_REQUIRED_BOTH_DIRECTION_ENABLED,
    54,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_nv_replace_warn,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_NV_REPLACE_WARN,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_nv_replace_warnDetails},

    {ELETTRONICSERVICES_IDX,
    diagnosisDynamic.elettronicservicesAlarm,
    ELETTRONICSERVICES_ALARM_POWER_SUPPLY_TOO_LOW,
    53,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_cb_insuf_input_voltage,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_CB_INSUF_INPUT_VOLTAGE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_cb_insuf_input_voltageDetails},

    {ELETTRONICSERVICES_IDX,
    diagnosisDynamic.elettronicservicesAlarm,
    ELETTRONICSERVICES_ALARM_POWER_SUPPLY_TOO_HIGH,
    53,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_cb_insuf_input_voltage,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_CB_INSUF_INPUT_VOLTAGE,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_cb_insuf_input_voltageDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_CB_MAINTENANCE,
    52,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_maintenance_warning,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_MAINTENANCE_WARNING,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_maintenance_warningDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_FE_MAINTENANCE_MATURE,
    52,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_maintenance_warning,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_MAINTENANCE_WARNING,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_maintenance_warningDetails},

    {CDT_IDX,
    diagnosisDynamic.coordinatorAlarm,
    CDT_ALARM_CB_UNCALIBRATED,
    51,
    &diagnosisStaticFrequentConstantDefault.configurableClassification_fe_nv_warning,
    DIAGNOSIS_GROUP_OPERATING_CONDITION,
    DIAGNOSIS_CONDITION_FE_NV_WARNING,
    NULL,
    &diagnosisStaticCyclic.diagnosisCondition_fe_nv_warningDetails}
};
//@CodeGen end@ <INPUT_TABLE>

//----------------------------------------------------------------------------------------------------------
//! Fast Output Table
//@CodeGen start@ <FAST_OUTPUT_TABLE>
#ifdef DIAGNOSIS_USE_CONFIGURABLE_BEHAVIOUR
const T_DIAGNOSIS_FASTOUTPUT_TABLE FASTOutputTable[FASTOUTPUT_TABLE_SIZE] = {
    {DIGITALOUTPUT_IDX,
    &inputTable[28],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[29],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[24],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[25],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[26],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[27],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[31],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[22],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior},

    {DIGITALOUTPUT_IDX,
    &inputTable[23],
    &diagnosisStaticFrequentConstantDefault.DigitalOutputAlarmBehavior}
};

const T_DIAGNOSIS_TABLE_ADDRESSING FASTOutputTableAddressing[MEMBER_IDX_NUM_ELEMENTS] = {
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,0},
{0,9},
{0,0},
{0,0},
{0,0},
{0,0}
};
#endif
//@CodeGen end@ <FAST_OUTPUT_TABLE>

//----------------------------------------------------------------------------------------------------------
//! Simulation Data
//lint -e{641} Giovanni Invernizzi 2007-06-26 Converting enum to int accepted
//lint -e{656} Giovanni Invernizzi 2007-06-26 Arithmetic operation uses (compatible) enum's accepted
//@CodeGen start@ <SIMULATION_TABLE>
const T_DIAGNOSIS_SIMULATION_OBJ_ADDRESSING simulationObjTable[SIMULATION_OBJ_TABLE_SIZE] = {
    {AI_IDX_aiAlarmSimulation,ANALOG_INPUT_ME},

    {CDT_IDX_coodinatorAlarmSimulation,COORDINATOR_ME},

    {DIGITALOUTPUT_IDX_alarmSimulation_DO,DIGITAL_OUTPUT_ME},

    {ELETTRONICSERVICES_IDX_electronicServicesAlarmSimulation,ELETTRONIC_SERVICES_ME},

    {FE_IDX_frontendAlarmSimulation,FRONT_END_INTERFACE_ME},

    {MAPPER_IDX_mapperAlarmSimulation,MAPPER_ME},

    {MVM_IDX_mvmAlarmSimulation,MVMEASUREMENT_ME},

    {SVM_IDX_svmAlarmSimulation,SVMEASUREMENT_ME},

    {TOTALIZER_IDX_totDiagnosisSimulation,TOTALIZER_ME}
};
//@CodeGen end@ <SIMULATION_TABLE>

//lint -e{641} -e{656}
//========add for simulation HMI mapper===============================================
const T_DIAGNOSIS_SIMULATION_MAPPER DiagnosisSimulationTable[SIMULATION_OBJ_TABLE_SIZE] = {
	{AI_IDX, 								DIAGNOSIS_IDX_analoginputAlarmSimulation, 			AI_IDX_aiAlarmSimulation},
    {CDT_IDX,							DIAGNOSIS_IDX_coordinatorAlarmSimulation,			CDT_IDX_coodinatorAlarmSimulation},
    {DIGITALOUTPUT_IDX,			DIAGNOSIS_IDX_digitaloutputAlarmSimulation,			DIGITALOUTPUT_IDX_alarmSimulation_DO},
    {ELETTRONICSERVICES_IDX,	DIAGNOSIS_IDX_elettronicservicesAlarmSimulation,	ELETTRONICSERVICES_IDX_electronicServicesAlarmSimulation},
    {FE_IDX,								DIAGNOSIS_IDX_frontendinterfaceAlarmSimulation, 	FE_IDX_frontendAlarmSimulation},
    {MAPPER_IDX,						DIAGNOSIS_IDX_mapperAlarmSimulation, 					MAPPER_IDX_mapperAlarmSimulation},
	{MVM_IDX,							DIAGNOSIS_IDX_mvmeasurementAlarmSimulation, 	MVM_IDX_mvmAlarmSimulation},
    {SVM_IDX,							DIAGNOSIS_IDX_svmeasurementAlarmSimulation,		SVM_IDX_svmAlarmSimulation},
    {TOTALIZER_IDX,					DIAGNOSIS_IDX_totalizerAlarmSimulation,					TOTALIZER_IDX_totDiagnosisSimulation}
};



