//----------------------------------------------------------------------------------------------------------
/*
 Copyright              Copyright ABB, 2006.
                        All rights reserved. Reproduction, modification,
                        use or disclosure to third parties without express
                        authority is forbidden.

 $Workfile: $
 $Revision: $
 $Archive: $

 System         SecondaryCalcs Subsystem (units handling)
 Module         T_DATA_OBJ_FLOWVALUES
 Description    Definition of class T_DATA_OBJ::FLOWVALUES

 <pre>
   object data types: ST_FLOAT, ST_E8, ST_E8

   Internally value is in base units [l/s].
   Externally is in associated engineering units.
   min and max value of descriptor are in base units.

   data-type of the object descriptor:  T_FLOWVALUES_DESCRIPTOR    T_FLOATUNITS_DESCRIPTOR

   data-type of the attribute (object) range-information: value:     T_RANGE_FLOAT
                                                          units:     T_RANGE_E8
                                                          unitsType: T_RANGE_E8

   Businessrules
     value has to be within min max range and is units-converted while reading and writing
     units is a member of the possible values defined by the table flowvaluesUnitsTable
     the nearest possible value to an illegal value is the old value.
 </pre>
 Remarks

*/
//----------------------------------------------------------------------------------------------------------
#include <intrinsics.h>
#include "System/Interface/system.h"
#include "System/Interface/common_type.h"
#include "RTOS/Interface/rtos.h"
#include "System/Interface/assert.h"
#include "T_DATA_OBJ/Interface/simple_type.h"
#include "T_DATA_OBJ/Interface/t_data_obj.h"
#include "T_DATA_OBJ/Interface/t_data_obj_rngflt.h"
#include "T_Unit/Interface/t_unit.h"
#include "UnitsOfMeasure/Interface/UnitsOfMeasure.h"
#include "HART/Interface/Hart.h"
//#include "..\..\interface\hart_unit_convert.h"

//Special units defines

//#define NOT_SUPPORTED                          0xFF
//#define SPEZIAL                                 253
//#define UNKNOWN                                 252


//TODO #define HART_UNITS_USE_CLASSIFICATION
//Added 20110426

#define HART_UNITS_USE_CLASSIFICATION

#define GTAB_CONV_HART_UNIT_TAB(unitsType)       const CONV_HART_UNIT_TAB tab##unitsType[]=
#define GENTRY_CONV_HART_UNIT_TAB(systemunit)    { systemunit , HART_##systemunit }

// TODO reduce constant-memory-usage, but this define is not possible
//#define GENTRY_CONV_HART_UNIT_TAB(unit)      #if( HART_##unit## != NOT_SUPORTED ) \
//                                          { unit, HART_##unit## },         \
//                                      #endif


//----------------------------------------------------------------------------------------------------------
// Extern declaration


//----------------------------------------------------------------------------------------------------------
// Private static conversion operations.

//----------------------------------------------------------------------------------------------------------

#define NOT_SUPPORTED     0xFF
//#define RESULT_ERROR      0xFF
//#define RESULT_OK         0x00

typedef struct _CONV_HART_UNIT_TAB
{
    TUSIGN8     systemUnit;
    TUSIGN8     hartUnit;

} CONV_HART_UNIT_TAB;



GTAB_CONV_HART_UNIT_TAB(UM_T_UNKNOWN_UNIT_GROUP)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_UKNOWN_UNIT),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_VELOCITY)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_METER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_METER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOMETER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_YARD_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_YARD_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_YARD_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILE_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KNOT),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_MASS)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND),
    GENTRY_CONV_HART_UNIT_TAB(UM_OUNCE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIGRAM),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAGRAM),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON),
    GENTRY_CONV_HART_UNIT_TAB(UM_SHORT_TON),
    GENTRY_CONV_HART_UNIT_TAB(UM_LONG_TON),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_MASS_FLOW)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_SHORT_TON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_SHORT_TON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_SHORT_TON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_SHORT_TON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_LONG_TON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_LONG_TON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_LONG_TON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_LONG_TON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPOUND_US_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPOUND_US_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPOUND_US_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPOUND_US_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_OUNCE_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_OUNCE_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_OUNCE_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_OUNCE_PER_DAY),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_VOLUME)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_LITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_INCH),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_FEET),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_YARD),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOLITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_IMPERIAL_GALLON),
    GENTRY_CONV_HART_UNIT_TAB(UM_US_GALLON),
    GENTRY_CONV_HART_UNIT_TAB(UM_BUSHEL),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_CENTIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAFEET),
    GENTRY_CONV_HART_UNIT_TAB(UM_CENTILITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLILITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOLITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGALITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_PINT),
    GENTRY_CONV_HART_UNIT_TAB(UM_QUART),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_LIQUID),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_FEDERAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGALLON),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_IMPERIAL_GALLON),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGABARREL),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_INCH),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_FEET),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAGALLON),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_NORM_VOLUME)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_CUBIC_METER_0C_1ATM     ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_LITER_0C_1ATM           ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_FOOT_60F_1ATM   ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_METER_20C_1ATM  ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_LITER_20C_1ATM        ),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_VOLUME_FLOW)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_LITER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_LITER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_LITER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_FEET_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_FEET_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_FEET_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_FEET_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_METER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_METER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_METER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_METER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_US_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_US_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_US_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_US_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_IMPERIAL_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_IMPERIAL_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_IMPERIAL_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_IMPERIAL_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_US_BEER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOLITER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGALITER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_US_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MICROMETER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MICROMETER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MICROMETER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MICROMETER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIMETER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIMETER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIMETER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIMETER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_CENTIMETER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_CENTIMETER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_CENTIMETER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_CENTIMETER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOMETER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOMETER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOMETER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOMETER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAMETER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAMETER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAMETER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAMETER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIFEET_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIFEET_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIFEET_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MILLIFEET_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOFEET_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOFEET_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOFEET_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_KILOFEET_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_CUBIC_MEGAFEET_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_INCH_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_INCH_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_INCH_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_INCH_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_FEET_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_FEET_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_FEET_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_ACRE_FEET_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_LITER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOLITER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGALITER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGALITER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOLITER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOLITER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOLITER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOLITER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOLITER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOLITER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_US_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_US_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_US_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_US_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_US_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_US_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_US_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_US_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_US_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_US_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_US_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_US_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_US_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_US_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_US_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_IMPERIAL_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_IMPERIAL_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_IMPERIAL_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_IMPERIAL_GALLON_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_IMPERIAL_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_IMPERIAL_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_IMPERIAL_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_IMPERIAL_GALLON_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_IMPERIAL_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_IMPERIAL_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_IMPERIAL_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_IMPERIAL_GALLON_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRO_IMPERIAL_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLI_IMPERIAL_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_IMPERIAL_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGA_IMPERIAL_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLION_GALLON_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROBARREL_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGABARREL_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGABARREL_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROBARREL_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROBARREL_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGABARREL_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROBARREL_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGABARREL_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_US_BEER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_US_BEER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOBARREL_US_BEER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_US_BEER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_US_BEER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_US_BEER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_US_BEER_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_US_BEER_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_US_BEER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBARREL_US_BEER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROBARREL_US_BEER_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROBARREL_US_BEER_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_LIQUID_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_LIQUID_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_LIQUID_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_FEDERAL_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_FEDERAL_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_FEDERAL_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_BARREL_FEDERAL_PER_DAY),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_NORMAL_VOLUME_FLOW)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_CUBIC_METER_PER_SECOND_0C_1ATM    ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_CUBIC_METER_PER_MINUTE_0C_1ATM    ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_CUBIC_METER_PER_HOUR_0C_1ATM      ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_CUBIC_METER_PER_DAY_0C_1ATM       ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_LITER_PER_SECOND_0C_1ATM          ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_LITER_PER_MINUTE_0C_1ATM          ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_LITER_PER_HOUR_0C_1ATM            ),
    GENTRY_CONV_HART_UNIT_TAB(UM_NORMAL_LITER_PER_DAY_0C_1ATM             ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_FEET_PER_MINUTE_60F_1ATM  ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_FEET_PER_HOUR_60F_1ATM    ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_METER_PER_SECOND_20C_1ATM ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_METER_PER_MINUTE_20C_1ATM ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_METER_PER_HOUR_20C_1ATM   ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_CUBIC_METER_PER_DAY_20C_1ATM    ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_LITER_PER_SECOND_20C_1ATM       ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_LITER_PER_MINUTE_20C_1ATM       ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_LITER_PER_HOUR_20C_1ATM         ),
    GENTRY_CONV_HART_UNIT_TAB(UM_STANDARD_LITER_PER_DAY_20C_1ATM          ),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_PRESSURE)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAPASCAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIPASCAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROPASCAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_PASCAL_U),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPASCAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_BAR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBAR),
    GENTRY_CONV_HART_UNIT_TAB(UM_ATMOSPHERE),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUNDFORCE_PER_SQUARE_INCH),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUNDFORCE_PER_SQUARE_INCH_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUNDFORCE_PER_SQUARE_INCH_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAMFORCE_PER_SQUARE_CENTIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAMFORCE_PER_SQUARE_CENTIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_GIGAPASCAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOPASCAL),
    GENTRY_CONV_HART_UNIT_TAB(UM_PASCAL_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_PASCAL_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_GIGAPASCA_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_GIGAPASCA_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAPASCAL_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAPASCAL_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPASCAL_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOPASCAL_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIPASCAL_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIPASCAL_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROPASCAL_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROPASCAL_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOPASCAL_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_HECTOPASCAL_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_60F_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_60F_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_4C_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_4C_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_68F_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_68F_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_4C_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_4C_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_68F_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_68F_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_ABSOLUTE_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_4C_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_4C_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_68F_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_68F_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_HG_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_HG_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_HG_0C_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_HG_0C_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_HG_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_HG_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_HG_0C_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_HG_0C_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_60F),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_4C),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_H2O_68F),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_4C),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_H2O_68F),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_4C),
    GENTRY_CONV_HART_UNIT_TAB(UM_FEET_H2O_68F),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_HG),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH_HG_0C),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_HG),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER_HG_0C),
    GENTRY_CONV_HART_UNIT_TAB(UM_TORR),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAMFORCE_PER_SQUARE_CENTIMETER_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAMFORCE_PER_SQUARE_CENTIMETER_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAMFORCE_PER_SQUARE_CENTIMETER_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAMFORCE_PER_SQUARE_CENTIMETER_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BAR_ABSOLUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BAR_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBAR_GAUGE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIBAR_ABSOLUTE),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_TEMPERATURE)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_KELVIN),
    GENTRY_CONV_HART_UNIT_TAB(UM_CELSIUS),
    GENTRY_CONV_HART_UNIT_TAB(UM_FAHRENHEIT),
    GENTRY_CONV_HART_UNIT_TAB(UM_RANKINE),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_MASS_DENSITY)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM_PER_CUBIC_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_CUBIC_CENTIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOGRAM_PER_LITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_CUBIC_INCH),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_CUBIC_FOOT),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAGRAM_PER_CUBIC_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_CUBIC_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_METRIC_TON_PER_CUBIC_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_MILLILITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_GRAM_PER_LITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_US_GALLON),
    GENTRY_CONV_HART_UNIT_TAB(UM_SHORT_TON_PER_CUBIC_YARD),
    GENTRY_CONV_HART_UNIT_TAB(UM_POUND_PER_GALLON),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROGRAM_PER_LITER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROGRAM_PER_CUBIC_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIGRAM_PER_LITER),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_EMF)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_VOLT),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIVOLT),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAVOLT),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOVOLT),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROVOLT),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_ELECTRIC_RESISTANCE)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_OHM),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOOHM),
    GENTRY_CONV_HART_UNIT_TAB(UM_GIGAOHM),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAOHM),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIOHM),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROOHM),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_TIME)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOSECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLISECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROSECOND),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_FREQUENCY)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_HERTZ),
    GENTRY_CONV_HART_UNIT_TAB(UM_TERAHERTZ),
    GENTRY_CONV_HART_UNIT_TAB(UM_GIGAHERTZ),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAHERTZ),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILO_HERTZ),
    GENTRY_CONV_HART_UNIT_TAB(UM_COUNT_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_PER_MINUTE),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_ELECTRIC_CURRENT)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIAMPERE),
    GENTRY_CONV_HART_UNIT_TAB(UM_AMPERE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOAMPERE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROAMPERE),
    GENTRY_CONV_HART_UNIT_TAB(UM_NANOAMPERE),
    GENTRY_CONV_HART_UNIT_TAB(UM_PICOAMPERE),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_CAPACITANCE)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_PICOFARAD),
    GENTRY_CONV_HART_UNIT_TAB(UM_FARAD),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIFARAD),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROFARAD),
    GENTRY_CONV_HART_UNIT_TAB(UM_NANOFARAD),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_INDUCTANCE)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_HENRY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIHENRY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROHENRY),
    GENTRY_CONV_HART_UNIT_TAB(UM_NANOHENRY),
    GENTRY_CONV_HART_UNIT_TAB(UM_PICOHENRY),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_ELECTRIC_CONDUCTIVITY)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_SIEMENS_PER_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGASIEMENS_PER_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOSIEMENS_PER_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLISIEMENS_PER_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROSIEMENS_PER_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLISIEMENS_PER_CENTIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROSIEMENS_PER_MILLIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROSIEMENS_PER_CENTIMETER),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_LENGTH)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_CENTIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLIMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICROMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_NANOMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_PICOMETER),
    GENTRY_CONV_HART_UNIT_TAB(UM_ANGSTROM),
    GENTRY_CONV_HART_UNIT_TAB(UM_FOOT),
    GENTRY_CONV_HART_UNIT_TAB(UM_INCH),
    GENTRY_CONV_HART_UNIT_TAB(UM_YARD),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILE),
    GENTRY_CONV_HART_UNIT_TAB(UM_NAUTICAL_MILE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MICRON),
    GENTRY_CONV_HART_UNIT_TAB(UM_MIL),
};


GTAB_CONV_HART_UNIT_TAB(UM_T_ENERGY)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_NEWTON_METER),
    GENTRY_CONV_HART_UNIT_TAB(UM_DEKA_THERM),
    GENTRY_CONV_HART_UNIT_TAB(UM_FOOTPOUND_FORCE),
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOWATT_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGACALORIE),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAJOULE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BRITISH_THERMAL_UNIT),
    GENTRY_CONV_HART_UNIT_TAB(UM_THOUSAND_BRITISH_THERMAL_UNIT),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_POWER)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_KILOWATT),
    GENTRY_CONV_HART_UNIT_TAB(UM_HORSEPOWER),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGACALORIE_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAJOULE_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MEGAWATT),
    GENTRY_CONV_HART_UNIT_TAB(UM_BRITISH_THERMAL_UNIT_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_BRITISH_THERMAL_UNIT_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_BRITISH_THERMAL_UNIT_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_BRITISH_THERMAL_UNIT_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_THOUSAND_BRITISH_THERMAL_UNIT_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_THOUSAND_BRITISH_THERMAL_UNIT_PER_MINUTE),
    GENTRY_CONV_HART_UNIT_TAB(UM_THOUSAND_BRITISH_THERMAL_UNIT_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_THOUSAND_BRITISH_THERMAL_UNIT_PER_DAY),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLION_BRITISH_THERMAL_UNIT_PER_SECOND),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLION_BRITISH_THERMAL_UNIT_PER_HOUR),
    GENTRY_CONV_HART_UNIT_TAB(UM_MILLION_BRITISH_THERMAL_UNIT_PER_DAY),
};

GTAB_CONV_HART_UNIT_TAB(UM_T_ANALYTICAL)
{
    GENTRY_CONV_HART_UNIT_TAB(UM_PERCENT),
    GENTRY_CONV_HART_UNIT_TAB(UM_PARTS_PER_MILLION),
    GENTRY_CONV_HART_UNIT_TAB(UM_PARTS_PER_BILLION),
    GENTRY_CONV_HART_UNIT_TAB(UM_PARTS_PER_THOUSAND),
    GENTRY_CONV_HART_UNIT_TAB(UM_PARTS_PER_TRILLION),    
    GENTRY_CONV_HART_UNIT_TAB(UM_PERCENT_VOLUME),
    GENTRY_CONV_HART_UNIT_TAB(UM_PERCENT_CONSISTENSY),
    GENTRY_CONV_HART_UNIT_TAB(UM_PERCENT_EXPLOSION_LEVEL),            
};

typedef struct _UNIT_TYPE_TAB
{
    TUSIGN8 systemUnitsType;
    #ifdef HART_UNITS_USE_CLASSIFICATION
    TUSIGN8 hartUnitsType;  //TODO omit HART-Units-Type Classification since HART6
    #endif
    const CONV_HART_UNIT_TAB *pUnitDescr;
    TUSIGN8 numUnits;

} UNIT_TYPE_TAB;

#ifdef HART_UNITS_USE_CLASSIFICATION
    #define GENTRY_UNIT_TYPE_TAB(unitsType)    { unitsType, HART_##unitsType, tab##unitsType, sizeof(tab##unitsType)/sizeof(CONV_HART_UNIT_TAB) }
#else
    #define GENTRY_UNIT_TYPE_TAB(unitsType)    { unitsType, tab##unitsType##, sizeof(tab##unitsType)/sizeof(CONV_HART_UNIT_TAB) }
#endif

//#define GENTRY_UNIT_TYPE_TAB(unitsType)      #if( unitsType > 0 )                                                                    \
//                                            { unitsType, tab##unitsType##, sizeof(tab##unitsType)/sizeof(CONV_HART_UNIT_TAB) }  \
//                                        #endif

// Table of units type codes.
const UNIT_TYPE_TAB TypeTab[] =
{
    GENTRY_UNIT_TYPE_TAB(UM_T_UNKNOWN_UNIT_GROUP),
    GENTRY_UNIT_TYPE_TAB(UM_T_VELOCITY),
    GENTRY_UNIT_TYPE_TAB(UM_T_MASS),
    GENTRY_UNIT_TYPE_TAB(UM_T_MASS_FLOW),
    GENTRY_UNIT_TYPE_TAB(UM_T_VOLUME),
    GENTRY_UNIT_TYPE_TAB(UM_T_NORM_VOLUME),
    GENTRY_UNIT_TYPE_TAB(UM_T_VOLUME_FLOW),
    GENTRY_UNIT_TYPE_TAB(UM_T_NORMAL_VOLUME_FLOW),
    GENTRY_UNIT_TYPE_TAB(UM_T_PRESSURE),
    GENTRY_UNIT_TYPE_TAB(UM_T_TEMPERATURE),
    GENTRY_UNIT_TYPE_TAB(UM_T_MASS_DENSITY),
    GENTRY_UNIT_TYPE_TAB(UM_T_EMF),
    GENTRY_UNIT_TYPE_TAB(UM_T_ELECTRIC_RESISTANCE),
    GENTRY_UNIT_TYPE_TAB(UM_T_TIME),
    GENTRY_UNIT_TYPE_TAB(UM_T_FREQUENCY),
    GENTRY_UNIT_TYPE_TAB(UM_T_ELECTRIC_CURRENT),
    GENTRY_UNIT_TYPE_TAB(UM_T_CAPACITANCE),
    GENTRY_UNIT_TYPE_TAB(UM_T_LENGTH),
    GENTRY_UNIT_TYPE_TAB(UM_T_ENERGY),
    GENTRY_UNIT_TYPE_TAB(UM_T_POWER),
    GENTRY_UNIT_TYPE_TAB(UM_T_ANALYTICAL),
};



//TODO header
//call with HART-defined unitCode and (maybe unknown) System-defined unitTypeCode
//success-return with System-defined unitCode and unitTypeCode
TBOOL HartConvUnitCodeFromHartUnit_HART(TUSIGN8 * pUnitCode, TUSIGN8 * pUnitTypeCode )
{
    TUSIGN8 unitTypeCounter;
    TUSIGN8 unitCounter;

    if( pUnitCode && pUnitTypeCode)
    {
        //value of NOT_SUPPORTED must be invalid at HART-Spec to have an exclusive identification...
        if(*pUnitCode != NOT_SUPPORTED)
        {
            //...and search makes sense
            for(unitTypeCounter = 0; unitTypeCounter < (sizeof(TypeTab)/sizeof(TypeTab[0])); unitTypeCounter++)
            {
                //value of HART_UM_T_UNKNOWN_UNIT_GROUP signs to search in all groups, first occurence bingo
                //this direction (HART-Unit to System-Unit) shall be 'only one occurence', because
                //the HART-Unit definition implicits the Unit-Group
                if( *pUnitTypeCode != UM_T_UNKNOWN_UNIT_GROUP )
                {
                    // a stated systemUnitsTypeCode...
                    if( TypeTab[unitTypeCounter].systemUnitsType != *pUnitTypeCode )
                    {
                        //...speeds up search
                        continue;
                    }
                }
                for(unitCounter = 0; unitCounter < TypeTab[unitTypeCounter].numUnits; unitCounter++)
                {
                    if(TypeTab[unitTypeCounter].pUnitDescr[unitCounter].hartUnit == *pUnitCode)
                    {
                        //return System-Type
                        *pUnitTypeCode = TypeTab[unitTypeCounter].systemUnitsType;
                        //return System-Unit
                        *pUnitCode = TypeTab[unitTypeCounter].pUnitDescr[unitCounter].systemUnit;
                        return eTRUE;
                    }
                }
            }
        }
    }
    return eFALSE;
}

//TODO header
//call with System-defined unitCode and unitTypeCode
//success-return with HART-defined unitCode
TBOOL HartConvUnitCodeFromSystemUnit_HART(TUSIGN8 * pUnitCode, TUSIGN8 * pUnitTypeCode)
{
    TUSIGN8 unitTypeCounter;
    TUSIGN8 unitCounter;

    if( pUnitCode && pUnitTypeCode )
    {
        //TODO if((*pUnitCode != NOT_SUPPORTED) && (*pUnitTypeCode != UM_T_UNKNOWN_UNIT_GROUP))
        {
            for(unitTypeCounter = 0; unitTypeCounter < (sizeof(TypeTab)/sizeof(TypeTab[0])); unitTypeCounter++)
            {
                if( TypeTab[unitTypeCounter].systemUnitsType != *pUnitTypeCode )
                {
                    continue;
                }
                for(unitCounter = 0; unitCounter < TypeTab[unitTypeCounter].numUnits; unitCounter++)
                {
                    if(TypeTab[unitTypeCounter].pUnitDescr[unitCounter].systemUnit == *pUnitCode)
                    {
                        //return HART-Unit
                        *pUnitCode = TypeTab[unitTypeCounter].pUnitDescr[unitCounter].hartUnit;
                        if( *pUnitCode == NOT_SUPPORTED )
                        {
                            *pUnitCode = HART_UM_UKNOWN_UNIT;
                        }
                        return eTRUE;
                    }
                }
            }
        }
    }
    return eFALSE;
}
#ifdef HART_UNITS_USE_CLASSIFICATION
//TODO header

TBOOL HartConvUnitTypeFromHartUnit_HART(TUSIGN8 * pHartUnitTypeCode, TUSIGN8 * pUnitTypeCode )
{
    TUSIGN8 unitTypeCounter;
    const TUSIGN8 Classific_Hart = 0x0;//unsupported

    if(*pHartUnitTypeCode == Classific_Hart)
    {
        *pUnitTypeCode = Classific_Hart;
        return eFALSE;
    }
    for(unitTypeCounter = 0; unitTypeCounter < (sizeof(TypeTab)/sizeof(TypeTab[0])); unitTypeCounter++)
    {
        if( TypeTab[unitTypeCounter].hartUnitsType  == *pHartUnitTypeCode )
        {
            *pUnitTypeCode = TypeTab[unitTypeCounter].systemUnitsType;
            return eTRUE;
        }
    }
    return eFALSE;
}

//TODO header
TBOOL HartConvUnitTypeFromSystemUnit_HART(TUSIGN8 * pUnitTypeCode, TUSIGN8 * pHartUnitTypeCode )
{
    TUSIGN8 unitTypeCounter;
    const TUSIGN8 Classific_Hart = 0x0;//unsupported

    if(*pUnitTypeCode == Classific_Hart)
    {
        *pHartUnitTypeCode = Classific_Hart;
        return eTRUE;
    }  
    for(unitTypeCounter = 0; unitTypeCounter < (sizeof(TypeTab)/sizeof(TypeTab[0])); unitTypeCounter++)
    {
        if( TypeTab[unitTypeCounter].systemUnitsType == *pUnitTypeCode )
        {
            *pHartUnitTypeCode = TypeTab[unitTypeCounter].hartUnitsType;
            return eTRUE;
        }
    }
    return eFALSE;
}

#endif
