// IncludeList_Constructor.h

//+@ HMIGen IncludeList_Constructor @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "constructorInclude.h"
#include "constructorDefault.h"

//-@ HMIGen IncludeList_Constructor @-

