// IncludeList_Diagnosis.h

//+@ HMIGen IncludeList_Diagnosis @+

// If the files generated by the diagnosis code generator are not saved to the ....Diagnosis\Interface\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "Diagnosis/interface/DiagnosisCompileTimeDefinitions.h"
#include "Diagnosis/interface/t_data_obj_alarm.h"
#include "Diagnosis/interface/t_data_obj_alarm_counter.h"
#include "Diagnosis/interface/diagnosis.h"
#include "Diagnosis/interface/Diagnosis_idx.h"
#include "Diagnosis/Source/diagnosis_types.h"
#include "Diagnosis/Source/diagnosis_table_default.h"

//-@ HMIGen IncludeList_Diagnosis @-

