// IncludeList_Layer2.h

//+@ HMIGen IncludeList_LowLevelLayer2 @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "Hmi/HmiGen/VT5/source/Layer2.h"

//-@ HMIGen IncludeList_LowLevelLayer2 @-

