// This file contains all HMI functions that access the I/O ports and all functions that control access to the I/0

#include "IncludeList_implementation.h"
#include "System/Interface/system.h"

#if(HOST_FRAMEWORK_VERSION < 0x020300)
    #include "../../common/interface/common_type.h"
    #include "../../embos/interface/rtos.h"
    #if defined(TYPE_4_IMPLEMENTATION) || defined(TYPE_5_IMPLEMENTATION)
        #include "../../common/interface/common_hardware.h"
    #endif
#else
    #include "System/Interface/common_type.h"
    #include "RTOS/Interface/rtos.h"
    #if defined(TYPE_4_IMPLEMENTATION) || defined(TYPE_5_IMPLEMENTATION)
        #include "../../system/interface/common_hardware.h"
    #endif
#endif

extern TBOOL InitController(TBOOL initFromMaster);

#pragma diag_suppress=Pm077
#pragma diag_suppress=Go003

//+@ HMIGen IncludeList_Layer2.c @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "Layer2.h"
#include "Layer2Functions.h"

//-@ HMIGen IncludeList_Layer2.c @-

#pragma diag_default=Go003
#pragma diag_default=Pm077

