#pragma diag_suppress=Go003

//#include "hmi_framework_definition.h"
#include "IncludeList_Implementation.h"
#include "System/Interface/system.h"

#if(HOST_FRAMEWORK_VERSION < 0x020300)
#include "../../common/interface/common_type.h"
#include "../../embos/interface/rtos.h"
#else
#include "System/Interface/common_type.h"
#include "RTOS/Interface/rtos.h"
#endif

#include "T_DATA_OBJ/Interface/simple_type.h"
#include "T_DATA_OBJ/Interface/t_data_obj.h"
#include "T_Unit/Interface/t_unit.h"

#include "Hmi/Interface/HMI_idx.h"
#include "Hmi/Interface/HMI.h"
#include "hmi_types.h"
#include "hmi_attributes.h"

#ifndef _FRAMETABLEDEFINITIONS_H
#include "frameTableDefinitions.h"
#endif

#ifndef _KEYSTATEDEFINITIONS_H
#include "keystateDefinitions.h"
#endif

#ifndef _ADJUSTER_H
#include "adjuster.h"
#endif

#ifndef _FRAMETABLE_H
#include "FrameTable.h"
#endif


//+@ HMIGen IncludeList_ValidityTest.c @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "frames.h"
#include "validityTest.h"
#include "validityTestFunctions.h"

//-@ HMIGen IncludeList_ValidityTest.c @-

