//-------------------------------------------------------------------------------------------------
/*
<pre>
 Copyright              Copyright ABB, 2009.
                        All rights reserved. Reproduction, modification,
                        use or disclosure to third parties without express
                        authority is forbidden.
 System         ModbusGen
 Module         ModbusRegisterTables.c
 Description    Register tables used by the Modbus subsystem
 Remarks        This is a code generated file. It should only be modified within the tags
                <MODBUS_GEN_HEADERS_START> and <MODBUS_GEN_HEADERS_END> and then only when the
                ModbusGen option 'Add Include Paths' is unchecked. This is used to disable
                the addition of header file includes for subsystems and data objects when
                nested includes are required that cannot be detected.
</pre>
*/
//-------------------------------------------------------------------------------------------------
#include "System/Interface/common_type.h"
// Included for the subsystem indexes used throughout the register tables
#include "System/Interface/system.h"
#include "RTOS/Interface/rtos.h"

#include "T_DATA_OBJ/Interface/simple_type.h"
#include "T_DATA_OBJ/Interface/t_data_obj.h"
#include "T_Unit/Interface/t_unit.h"
#include "Coordinator/Interface/subsystem_idx.h"
#include "Coordinator/Interface/Coordinator_idx.h"
#include "Modbus/Interface/Modbus_idx.h"
#include "Modbus/Interface/t_data_obj_modbus_diag.h"
#include "Modbus/Interface/t_data_obj_modbus_diag_history.h"

// For function prototypes placed in tables and types defined in the register table
// header file
#include "Modbus/Source/Modbus_register_table.h"
#include "Modbus/Source/Modbus_register_tables.h"
#include "Modbus/Source/Modbus_register_table_coil_buffer.h" 
#include "Modbus/Source/Modbus_register_table_string_buffer.h"
#include "Modbus/Source/Modbus_register_table_single_buffer.h"
#include "Modbus/Source/Modbus_register_table_coil_objects.h"
#include "Modbus/Source/Modbus_register_table_string_objects.h"
#include "Modbus/Source/Modbus_register_table_single_objects.h"
#include "Modbus/Source/Modbus_register_table_objects.h"

//<MODBUS_GEN_HEADERS_START>

#include "ARM/Interface/arm_idx.h"
#include "DigitalOutput/Interface/DigitalOutput_idx.h"
#include "SVMeasurement/Interface/SVMeasurement_idx.h"
#include "HART/Interface/Hart_idx.h"
#include "Hmi/Interface/HMI_idx.h"
#include "MVMeasurement/Interface/MVMeasurement_idx.h"
#include "ElettronicServices/Interface/ElettronicServices_idx.h"
#include "Mapper/Interface/Mapper_idx.h"
#include "Totalizer/Interface/Totalizer_idx.h"
#include "AnalogInput/Interface/AnalogInput_idx.h"
#include "ServicePort/Interface/ServicePort_idx.h"
#include "Ethernet/Interface/Ethernet_idx.h"
#include "WebServer/Interface/WebServer_idx.h"
#include "Totalizer/Interface/t_data_obj_totdisp.h"
#include "T_DATA_OBJ/Interface/t_data_obj_tabenum8.h"
#include "T_DATA_OBJ/Interface/t_data_obj_units.h"
#include "T_DATA_OBJ/Interface/t_data_obj_floatunits.h"
#include "T_DATA_OBJ/Interface/t_data_obj_float_fixedunit.h"
#include "T_DATA_OBJ/Interface/t_data_obj_floatfloatunits.h"
#include "T_DATA_OBJ/Interface/t_data_obj_uom_pf.h"
#include "T_DATA_OBJ/Interface/t_data_obj_dev_rngflt.h"
#include "T_DATA_OBJ/Interface/t_data_obj_rngflt.h"

//<MODBUS_GEN_HEADERS_END>

//<MODBUS_GEN_CODE_START>
const TModbusRegisterTableItem ReadOnly_1bit_Bool_B1RO1_registerTable[] = 
{
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte0Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte1Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte2Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte3Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte4Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiag,
		MODBUS_DIAG_diagByte5Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte0Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte1Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte2Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte3Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte4Bit7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_mbDiagHis,
		MODBUS_DIAG_HIS_diagHisByte5Bit7
	}, 
} ;

const TModbusRegisterTableItem Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable[] = 
{
	{
		MAPPER_IDX,
		MAPPER_IDX_diagDeviceStatus,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagDeviceStatus,
		1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagDeviceStatus,
		2
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagDeviceStatus,
		3
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagDeviceStatus,
		4
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagDeviceStatus,
		5
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagHistory,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagHistory,
		1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagHistory,
		2
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagHistory,
		3
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagHistory,
		4
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagHistory,
		5
	},
} ;

const TModbusRegisterTableItem Float_32bit_ReadOnly_dynamic_F32ROD_registerTable[] = 
{
	{
		SVM_IDX,
		SVM_IDX_QDPercentage,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_QvDampedObj,
		UOM_PF_value_0
	},
	{
		SVM_IDX,
		SVM_IDX_QvPercentage,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QvPartialDampedObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QmDampedObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QnDampedObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QnPartialDampedObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QpDampedObj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_temperature_Damped_Obj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvContent,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvDensityObj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_frequency_Damped_Obj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureSensor_Obj,
		UOM_PF_value_0
	},
} ;

const TModbusRegisterTableItem Double_64bit_ReadOnly_dynamic_D64ROD_registerTable[] = 
{
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totDispQv,
		TOTDISP_value
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totDispQn,
		TOTDISP_value
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totDispQm,
		TOTDISP_value
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totDispQvPartial,
		TOTDISP_value
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totDispQnPartial,
		TOTDISP_value
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totDispEnergy,
		TOTDISP_value
	},
} ;

const TModbusRegisterTableItem Character_8bit_ReadOnly_C8RO_registerTable[] = 
{
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensorID,
		8
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensorSapErpNo,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensorCalDate,
		12
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensorCalCertNo,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensorCalLocation,
		32
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_tranType,
		12
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_tranID,
		8
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_tranSapErpNo,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_swRevisionHmi_transmitter,
		8
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_hwRevisionHmi_transmitter,
		8
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_swRevisionHmi_fe,
		8
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_hwRevisionHmi_fe,
		8
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_tranCalDate,
		12
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_tranCalCertNo,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_manufacturer,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_street,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_city,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_phone,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensorLocationTag,
		20
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_sensoTag,
		20
	},
} ;

const TModbusRegisterTableItem Usigned_Integer_8bit_ReadOnly_U8RO_registerTable[] = 
{
	{
		CDT_IDX,
		CDT_IDX_converterType,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_vortexmeterSize,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_swirlmeterSize,
		0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		1
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		2
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		3
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		4
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		5
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		6
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_bootloaderRevision,
		7
	},
	{
		ARM_IDX,
		ARM_IDX_readOnlySwitchStatus,
		0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_autozeroStatus,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_logicValue,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_calibrationStatus,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KLinearisation,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KSET,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_vbrFilNumCoef,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_lockMinIntPeriod,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_lockMaxIntPeriod,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_lockEstimation,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_accuracyHigh,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_accuracyMiddle,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_accuracyLow,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_analogGain,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_gainCtrl,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_gainMaxShift,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_lowFlowThreshOn,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_staticDecimation,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_middleBufDecimation,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_freqMinMarginPer,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_freqMaxMarginPer,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_forceReplace,
		0
	},
} ;

const TModbusRegisterTableItem Usigned_Integer_16bit_ReadOnly_U16RO_registerTable[] = 
{
	{
		SERVICEPORT_IDX,
		SERVICEPORT_IDX_baudRate,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_sigAmplitude,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_vbrAmplitude,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_sigMagnitude,
		0
	},
} ;

const TModbusRegisterTableItem Signed_Integer_16bit_ReadOnly_S16RO_registerTable[] = 
{
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_snrThreshold,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_spanUpperRange,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_vbrFilStep,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_gainLowThresh,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_gainHighThresh,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_gainMarginFreq,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_lowFlowThreshCoef,
		0
	},
} ;

const TModbusRegisterTableItem Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable[] = 
{
	{
		CDT_IDX,
		CDT_IDX_frontendOperationHour,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_totalWorkingTimeHour,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_pulseNum,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQvOverrollCnt,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQnOverrollCnt,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQmOverrollCnt,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totEnergyOverrollCnt,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQvPartialOverrollCnt,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQnPartialOverrollCnt,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_frontendMaintenance,
		0
	},
} ;

const TModbusRegisterTableItem Float_32bit_ReadOnly_F32RO_registerTable[] = 
{
	{
		SVM_IDX,
		SVM_IDX_QvMaxDNObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QvPartialMaxDNObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QmMaxDNObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QnMaxDNObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QnPartialMaxDNObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QpMaxDNObj,
		UOM_PF_value_0
	},
	{
		SVM_IDX,
		SVM_IDX_Re,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvTExtObj,
		UOM_PF_value_0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_elettronicTemperature_Obj,
		UOM_PF_value_0
	},
	{
		AI_IDX,
		AI_IDX_aiTempCurr,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_frequencyValue,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totOverrollBase,
		0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_ambientTemperatureMax_obj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureMaxRecord_obj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_snr,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KAverageLiquid,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		1
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		2
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		3
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		4
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		5
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		6
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquid,
		7
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		1
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		2
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		3
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		4
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		5
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		6
	},
	{
		SVM_IDX,
		SVM_IDX_KLiquidFreq,
		7
	},
	{
		SVM_IDX,
		SVM_IDX_KAverageGas,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		1
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		2
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		3
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		4
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		5
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		6
	},
	{
		SVM_IDX,
		SVM_IDX_KGas,
		7
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		1
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		2
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		3
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		4
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		5
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		6
	},
	{
		SVM_IDX,
		SVM_IDX_KGasFreq,
		7
	},
	{
		CDT_IDX,
		CDT_IDX_maxFlowFreq,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_minFlowFreq,
		0
	},
} ;

const TModbusRegisterTableItem Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable[] = 
{
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		8
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		9
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		10
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		11
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		12
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		13
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		14
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		15
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		16
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		17
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		18
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		19
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		20
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		21
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		22
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		23
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		24
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		25
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		26
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		27
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		28
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		29
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		30
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister1,
		31
	},
} ;

const TModbusRegisterTableItem Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable[] = 
{
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		8
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		9
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		10
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		11
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		12
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		13
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		14
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		15
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		16
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		17
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		18
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		19
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		20
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		21
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		22
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		23
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		24
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		25
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		26
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		27
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		28
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		29
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		30
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_ScanRegister2,
		31
	},
} ;

const TModbusRegisterTableItem Character_8bit_ReadWrite_C8RW_registerTable[] = 
{
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_tranCalLocation,
		32
	},
	{
		ETH_IDX,
		ETH_IDX_hostName,
		31
	},
	{
		ETH_IDX,
		ETH_IDX_domainName,
		31
	},
	{
		CDT_IDX,
		CDT_IDX_internalRTDPassword,
		6
	},
	{
		CDT_IDX,
		CDT_IDX_analogInputPassword,
		6
	},
	{
		CDT_IDX,
		CDT_IDX_energyFlowPassword,
		6
	},
} ;

const TModbusRegisterTableItem Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable[] = 
{
	{
		HMI_IDX,
		HMI_IDX_language,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_operatingMode,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_outputMode,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_lgcActState,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_QvObj,
		UOM_PF_unit
	},
	{
		MVM_IDX,
		MVM_IDX_QmObj,
		UOM_PF_unit
	},
	{
		MVM_IDX,
		MVM_IDX_QnObj,
		UOM_PF_unit
	},
	{
		MVM_IDX,
		MVM_IDX_QpDampedObj,
		UOM_PF_unit
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvDensityObj,
		UOM_PF_unit
	},
	{
		CDT_IDX,
		CDT_IDX_temperature_Obj,
		UOM_PF_unit
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureObj,
		UOM_PF_unit
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQvUnit,
		UNITS_unitsCode
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQmUnit,
		UNITS_unitsCode
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQnUnit,
		UNITS_unitsCode
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totEnergyUnit,
		UNITS_unitsCode
	},
	{
		AI_IDX,
		AI_IDX_aiSelection,
		0
	},
	{
		AI_IDX,
		AI_IDX_aiExternalCutOffOption,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_liquidCorrection,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_gasDensitySelection,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_gasRef,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_gasComputeType,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_steamType,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_actualDensitySelection,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_steamPwrrFR,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_SetPassword_StandardLevel,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_SetPassword_StandardLevel,
		1
	},
	{
		HMI_IDX,
		HMI_IDX_SetPassword_StandardLevel,
		2
	},
	{
		HMI_IDX,
		HMI_IDX_SetPassword_StandardLevel,
		3
	},
	{
		HMI_IDX,
		HMI_IDX_SetPassword_StandardLevel,
		4
	},
	{
		HMI_IDX,
		HMI_IDX_SetPassword_StandardLevel,
		5
	},
	{
		ARM_IDX,
		ARM_IDX_serviceAccountSwitch,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_ext_algSelection,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_vbrCorrectionOn,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_displayMode_1,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_1_1,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_1_2,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_1_3,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_1_bargraph,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_displayMode_2,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_2_1,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_2_2,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_2_3,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_2_bargraph,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_displayMode_3,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_3_1,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_3_2,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_3_3,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_3_bargraph,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_displayMode_4,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_4_1,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_4_2,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_4_3,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_mainOperatorView_4_bargraph,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_autoscrollEnable,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_customDP_1,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_customDP_2,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_DateFormat,
		0
	},
	{
		HMI_IDX,
		HMI_IDX_displayTest,
		0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_modeLCDLight,
		0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_switchBLE,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_generalAlarm,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_minFlowrateAlarm,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_maxFlowrateAlarm,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_maxTemperatureAlarm,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_minTemperatureAlarm,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_lowFlowCutOff,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_reaction_InputFail,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagMaintainMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagFunCheckMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagOffSpecMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagMinFlowMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagMaxFlowMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagFlow103Mask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagLowCutoffMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagTSensorFailMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagTSensorOffSpecMask,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagTxSensorOffSpecMask,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_selectedMainProtocol,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_useDhcp,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_enableProfinetIo,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_enableModbusTcp,
		0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_modbusIEEEFormat,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_enableWebserver,
		0
	},
	{
		WEBSRV_IDX,
		WEBSRV_IDX_defaultState,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_simulationMode,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_QvSimObj,
		UOM_PF_unit
	},
	{
		MVM_IDX,
		MVM_IDX_QmSimObj,
		UOM_PF_unit
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureSim_Obj,
		UOM_PF_unit
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_lgcSimCmd,
		0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagSimulationType,
		0
	},
} ;

const TModbusRegisterTableItem Signed_Integer_16bit_ReadWrite_S16RW_registerTable[] = 
{
	{
		CDT_IDX,
		CDT_IDX_lowFlowThresh,
		0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_simuPulsesNum,
		0
	},
} ;

const TModbusRegisterTableItem Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable[] = 
{
	{
		ETH_IDX,
		ETH_IDX_hostAddress,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_subnetMask,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_gatewayAddress,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_ntpServerAddress,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_dnsAddress,
		0
	},
	{
		WEBSRV_IDX,
		WEBSRV_IDX_sessionTimeoutInMinutes,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_ipStats,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_port1EthStatsHMI,
		0
	},
	{
		ETH_IDX,
		ETH_IDX_port1EthStatsHMI,
		1
	},
	{
		ETH_IDX,
		ETH_IDX_port1EthStatsHMI,
		2
	},
	{
		ETH_IDX,
		ETH_IDX_port1EthStatsHMI,
		3
	},
	{
		CDT_IDX,
		CDT_IDX_BothMaintenanceCycle,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_tranMaintenanceCyc,
		0
	},
} ;

const TModbusRegisterTableItem Float_32bit_ReadWrite_F32RW_registerTable[] = 
{
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_pulseFactor,
		FLOAT_FIXEDUNIT_value
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_pulseWidth,
		FLOAT_FIXEDUNIT_value
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_minFrequency,
		FLOAT_FIXEDUNIT_value
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_maxFrequency,
		FLOAT_FIXEDUNIT_value
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvTExtRangeObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvTExtRangeObj,
		UOM_PF_value_1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureRangeRelativeObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureRangeRelativeObj,
		UOM_PF_value_1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureRangeObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureRangeObj,
		UOM_PF_value_1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvDensityRangeObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvDensityRangeObj,
		UOM_PF_value_1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvContentRange,
		DEV_RNGFLT_hiLim
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvContentRange,
		DEV_RNGFLT_loLim
	},
	{
		CDT_IDX,
		CDT_IDX_temperature_range_Obj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_temperature_range_Obj,
		UOM_PF_value_1
	},
	{
		MVM_IDX,
		MVM_IDX_volumeExpandBeta1,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_densityExpandBeta2,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_heatCapacity,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_calorificEnergy,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_densigyRefObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvDensityPresetObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_refTemperatureObj,
		UOM_PF_value_0
	},
	{
		CDT_IDX,
		CDT_IDX_temperaturePreset_Obj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvTExtPresetObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressurePresetObj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvContentPreset,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_QvRangeObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QnRangeObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QvPartialRangeObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QnPartialRangeObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QmRangeObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QpRangeObj,
		UOM_PF_value_0
	},
	{
		SVM_IDX,
		SVM_IDX_QvDampingTime,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QnDampingTime,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QvPartialDampingTime,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QnPartialDampingTime,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QmDampingTime,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QpDampingTime,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_temperature_DampingTime,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_QvLowCutOff,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_dynViscosity,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureOffsetCorrectUserDisp,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QAlmRange,
		RANGEFLT_loLim
	},
	{
		MVM_IDX,
		MVM_IDX_QAlmRange,
		RANGEFLT_hiLim
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureAlmRange_obj,
		UOM_PF_value_1
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureAlmRange_obj,
		UOM_PF_value_0
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureAlmRangeObj,
		UOM_PF_value_1
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_dvPressureAlmRangeObj,
		UOM_PF_value_0
	},
	{
		SVM_IDX,
		SVM_IDX_ReAlmLimits,
		0
	},
	{
		SVM_IDX,
		SVM_IDX_QvSimObj,
		UOM_PF_value_0
	},
	{
		SVM_IDX,
		SVM_IDX_QvPerSim,
		0
	},
	{
		MVM_IDX,
		MVM_IDX_QmSimObj,
		UOM_PF_value_0
	},
	{
		MVM_IDX,
		MVM_IDX_QmPerSim,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_temperatureSim_Obj,
		UOM_PF_value_0
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_elettronicTemperatureSimulation_Obj,
		UOM_PF_value_0
	},
	{
		DIGITALOUTPUT_IDX,
		DIGITALOUTPUT_IDX_simuFrequency,
		0
	},
	{
		AI_IDX,
		AI_IDX_aiSimulationData,
		0
	},
	{
		CDT_IDX,
		CDT_IDX_frequency_SimObj,
		UOM_PF_value_0
	},
} ;

const TModbusRegisterTableItem Double_64bit_ReadWrite_D64RW_registerTable[] = 
{
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQvPresetValue,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQnPresetValue,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQmPresetValue,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totEnergyPresetValue,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQvPartialPresetValue,
		0
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_totQnPartialPresetValue,
		0
	},
} ;

const TModbusRegisterTableItem Action_8bit_WriteOnly_A8WO_registerTable[] = 
{
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_writeAutoZero,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		MAPPER_IDX,
		MAPPER_IDX_diagClearHistory,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_writeSelfDiagnosis,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartAllTotalizr,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartQvTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartQnTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartQmTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartEnergyTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartQvPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StartQnPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopAllTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopQvTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopQnTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopQmTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopEnergyTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopQvPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_StopQnPartialtotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetAllTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQvTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQnTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQmTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetEnergyTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQvPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQnPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_PresetAllTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQvTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQnTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQmTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_PresetEnergyTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_ResetQvPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		TOTALIZER_IDX,
		TOTALIZER_IDX_PresetQnPartialTotalizer,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_resetCB_Runhour,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_resetFE_Runhour,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_readParameters,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_writeParameters,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_saveCustomerDef,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_saveFactoryDef,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_resetCustomerDef,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		CDT_IDX,
		CDT_IDX_resetFactoryDef,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_saveAllAsDefault,
		(TUSIGN16)WHOLE_OBJECT
	},
	{
		ELETTRONICSERVICES_IDX,
		ELETTRONICSERVICES_IDX_resetAllToDefault,
		(TUSIGN16)WHOLE_OBJECT
	},
} ;

const TModbusRegisterTableItem Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable[] = 
{
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		8
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		9
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		10
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		11
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		12
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		13
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		14
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		15
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		16
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		17
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		18
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		19
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		20
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		21
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		22
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		23
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		24
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		25
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		26
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		27
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		28
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		29
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		30
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister1,
		31
	},
} ;

const TModbusRegisterTableItem Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable[] = 
{
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		0
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		1
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		2
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		3
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		4
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		5
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		6
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		7
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		8
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		9
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		10
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		11
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		12
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		13
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		14
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		15
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		16
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		17
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		18
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		19
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		20
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		21
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		22
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		23
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		24
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		25
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		26
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		27
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		28
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		29
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		30
	},
	{
		MODBUS_IDX,
		MODBUS_IDX_configScanRegister2,
		31
	},
} ;

const TUSIGN16 ReadOnly_1bit_Bool_B1RO1_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN8),
} ;

const TUSIGN16 ReadOnly_1bit_Bool_B1RO1_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2),
} ;

const TModbusRegisterTableDataDescriptor ReadOnly_1bit_Bool_B1RO1_registerTable_data_descriptor =
{
	ReadOnly_1bit_Bool_B1RO1_registerTable_data_descriptor_attribute_byte_sizes,
	ReadOnly_1bit_Bool_B1RO1_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN8)),
	((sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2)),
} ;

const TUSIGN16 Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN8),
} ;

const TUSIGN16 Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2),
} ;

const TModbusRegisterTableDataDescriptor Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable_data_descriptor =
{
	Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable_data_descriptor_attribute_byte_sizes,
	Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN8)),
	((sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2)),
} ;

const TUSIGN16 Float_32bit_ReadOnly_dynamic_F32ROD_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TFLOAT),
} ;

const TUSIGN16 Float_32bit_ReadOnly_dynamic_F32ROD_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TFLOAT)% 2 > 0)?(sizeof(TFLOAT)/2) + (sizeof(TFLOAT) % 2):(sizeof(TFLOAT)/2),
} ;

const TModbusRegisterTableDataDescriptor Float_32bit_ReadOnly_dynamic_F32ROD_registerTable_data_descriptor =
{
	Float_32bit_ReadOnly_dynamic_F32ROD_registerTable_data_descriptor_attribute_byte_sizes,
	Float_32bit_ReadOnly_dynamic_F32ROD_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TFLOAT)),
	((sizeof(TFLOAT)% 2 > 0)?(sizeof(TFLOAT)/2) + (sizeof(TFLOAT) % 2):(sizeof(TFLOAT)/2)),
} ;

const TUSIGN16 Double_64bit_ReadOnly_dynamic_D64ROD_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TDOUBLE),
} ;

const TUSIGN16 Double_64bit_ReadOnly_dynamic_D64ROD_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TDOUBLE)% 2 > 0)?(sizeof(TDOUBLE)/2) + (sizeof(TDOUBLE) % 2):(sizeof(TDOUBLE)/2),
} ;

const TModbusRegisterTableDataDescriptor Double_64bit_ReadOnly_dynamic_D64ROD_registerTable_data_descriptor =
{
	Double_64bit_ReadOnly_dynamic_D64ROD_registerTable_data_descriptor_attribute_byte_sizes,
	Double_64bit_ReadOnly_dynamic_D64ROD_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TDOUBLE)),
	((sizeof(TDOUBLE)% 2 > 0)?(sizeof(TDOUBLE)/2) + (sizeof(TDOUBLE) % 2):(sizeof(TDOUBLE)/2)),
} ;

const TUSIGN16 Character_8bit_ReadOnly_C8RO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TCHAR),
} ;

const TUSIGN16 Character_8bit_ReadOnly_C8RO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TCHAR)% 2 > 0)?(sizeof(TCHAR)/2) + (sizeof(TCHAR) % 2):(sizeof(TCHAR)/2),
} ;

const TModbusRegisterTableDataDescriptor Character_8bit_ReadOnly_C8RO_registerTable_data_descriptor =
{
	Character_8bit_ReadOnly_C8RO_registerTable_data_descriptor_attribute_byte_sizes,
	Character_8bit_ReadOnly_C8RO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TCHAR)),
	((sizeof(TCHAR)% 2 > 0)?(sizeof(TCHAR)/2) + (sizeof(TCHAR) % 2):(sizeof(TCHAR)/2)),
} ;

const TUSIGN16 Usigned_Integer_8bit_ReadOnly_U8RO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN8),
} ;

const TUSIGN16 Usigned_Integer_8bit_ReadOnly_U8RO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2),
} ;

const TModbusRegisterTableDataDescriptor Usigned_Integer_8bit_ReadOnly_U8RO_registerTable_data_descriptor =
{
	Usigned_Integer_8bit_ReadOnly_U8RO_registerTable_data_descriptor_attribute_byte_sizes,
	Usigned_Integer_8bit_ReadOnly_U8RO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN8)),
	((sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2)),
} ;

const TUSIGN16 Usigned_Integer_16bit_ReadOnly_U16RO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN16),
} ;

const TUSIGN16 Usigned_Integer_16bit_ReadOnly_U16RO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2),
} ;

const TModbusRegisterTableDataDescriptor Usigned_Integer_16bit_ReadOnly_U16RO_registerTable_data_descriptor =
{
	Usigned_Integer_16bit_ReadOnly_U16RO_registerTable_data_descriptor_attribute_byte_sizes,
	Usigned_Integer_16bit_ReadOnly_U16RO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN16)),
	((sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2)),
} ;

const TUSIGN16 Signed_Integer_16bit_ReadOnly_S16RO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TINT16),
} ;

const TUSIGN16 Signed_Integer_16bit_ReadOnly_S16RO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TINT16)% 2 > 0)?(sizeof(TINT16)/2) + (sizeof(TINT16) % 2):(sizeof(TINT16)/2),
} ;

const TModbusRegisterTableDataDescriptor Signed_Integer_16bit_ReadOnly_S16RO_registerTable_data_descriptor =
{
	Signed_Integer_16bit_ReadOnly_S16RO_registerTable_data_descriptor_attribute_byte_sizes,
	Signed_Integer_16bit_ReadOnly_S16RO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TINT16)),
	((sizeof(TINT16)% 2 > 0)?(sizeof(TINT16)/2) + (sizeof(TINT16) % 2):(sizeof(TINT16)/2)),
} ;

const TUSIGN16 Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN32),
} ;

const TUSIGN16 Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN32)% 2 > 0)?(sizeof(TUSIGN32)/2) + (sizeof(TUSIGN32) % 2):(sizeof(TUSIGN32)/2),
} ;

const TModbusRegisterTableDataDescriptor Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable_data_descriptor =
{
	Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable_data_descriptor_attribute_byte_sizes,
	Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN32)),
	((sizeof(TUSIGN32)% 2 > 0)?(sizeof(TUSIGN32)/2) + (sizeof(TUSIGN32) % 2):(sizeof(TUSIGN32)/2)),
} ;

const TUSIGN16 Float_32bit_ReadOnly_F32RO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TFLOAT),
} ;

const TUSIGN16 Float_32bit_ReadOnly_F32RO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TFLOAT)% 2 > 0)?(sizeof(TFLOAT)/2) + (sizeof(TFLOAT) % 2):(sizeof(TFLOAT)/2),
} ;

const TModbusRegisterTableDataDescriptor Float_32bit_ReadOnly_F32RO_registerTable_data_descriptor =
{
	Float_32bit_ReadOnly_F32RO_registerTable_data_descriptor_attribute_byte_sizes,
	Float_32bit_ReadOnly_F32RO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TFLOAT)),
	((sizeof(TFLOAT)% 2 > 0)?(sizeof(TFLOAT)/2) + (sizeof(TFLOAT) % 2):(sizeof(TFLOAT)/2)),
} ;

const TUSIGN16 Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN16),
} ;

const TUSIGN16 Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2),
} ;

const TModbusRegisterTableDataDescriptor Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable_data_descriptor =
{
	Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable_data_descriptor_attribute_byte_sizes,
	Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN16)),
	((sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2)),
} ;

const TUSIGN16 Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN16),
} ;

const TUSIGN16 Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2),
} ;

const TModbusRegisterTableDataDescriptor Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable_data_descriptor =
{
	Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable_data_descriptor_attribute_byte_sizes,
	Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN16)),
	((sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2)),
} ;

const TUSIGN16 Character_8bit_ReadWrite_C8RW_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TCHAR),
} ;

const TUSIGN16 Character_8bit_ReadWrite_C8RW_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TCHAR)% 2 > 0)?(sizeof(TCHAR)/2) + (sizeof(TCHAR) % 2):(sizeof(TCHAR)/2),
} ;

const TModbusRegisterTableDataDescriptor Character_8bit_ReadWrite_C8RW_registerTable_data_descriptor =
{
	Character_8bit_ReadWrite_C8RW_registerTable_data_descriptor_attribute_byte_sizes,
	Character_8bit_ReadWrite_C8RW_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TCHAR)),
	((sizeof(TCHAR)% 2 > 0)?(sizeof(TCHAR)/2) + (sizeof(TCHAR) % 2):(sizeof(TCHAR)/2)),
} ;

const TUSIGN16 Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN8),
} ;

const TUSIGN16 Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2),
} ;

const TModbusRegisterTableDataDescriptor Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable_data_descriptor =
{
	Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable_data_descriptor_attribute_byte_sizes,
	Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN8)),
	((sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2)),
} ;

const TUSIGN16 Signed_Integer_16bit_ReadWrite_S16RW_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TINT16),
} ;

const TUSIGN16 Signed_Integer_16bit_ReadWrite_S16RW_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TINT16)% 2 > 0)?(sizeof(TINT16)/2) + (sizeof(TINT16) % 2):(sizeof(TINT16)/2),
} ;

const TModbusRegisterTableDataDescriptor Signed_Integer_16bit_ReadWrite_S16RW_registerTable_data_descriptor =
{
	Signed_Integer_16bit_ReadWrite_S16RW_registerTable_data_descriptor_attribute_byte_sizes,
	Signed_Integer_16bit_ReadWrite_S16RW_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TINT16)),
	((sizeof(TINT16)% 2 > 0)?(sizeof(TINT16)/2) + (sizeof(TINT16) % 2):(sizeof(TINT16)/2)),
} ;

const TUSIGN16 Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN32),
} ;

const TUSIGN16 Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN32)% 2 > 0)?(sizeof(TUSIGN32)/2) + (sizeof(TUSIGN32) % 2):(sizeof(TUSIGN32)/2),
} ;

const TModbusRegisterTableDataDescriptor Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable_data_descriptor =
{
	Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable_data_descriptor_attribute_byte_sizes,
	Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN32)),
	((sizeof(TUSIGN32)% 2 > 0)?(sizeof(TUSIGN32)/2) + (sizeof(TUSIGN32) % 2):(sizeof(TUSIGN32)/2)),
} ;

const TUSIGN16 Float_32bit_ReadWrite_F32RW_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TFLOAT),
} ;

const TUSIGN16 Float_32bit_ReadWrite_F32RW_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TFLOAT)% 2 > 0)?(sizeof(TFLOAT)/2) + (sizeof(TFLOAT) % 2):(sizeof(TFLOAT)/2),
} ;

const TModbusRegisterTableDataDescriptor Float_32bit_ReadWrite_F32RW_registerTable_data_descriptor =
{
	Float_32bit_ReadWrite_F32RW_registerTable_data_descriptor_attribute_byte_sizes,
	Float_32bit_ReadWrite_F32RW_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TFLOAT)),
	((sizeof(TFLOAT)% 2 > 0)?(sizeof(TFLOAT)/2) + (sizeof(TFLOAT) % 2):(sizeof(TFLOAT)/2)),
} ;

const TUSIGN16 Double_64bit_ReadWrite_D64RW_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TDOUBLE),
} ;

const TUSIGN16 Double_64bit_ReadWrite_D64RW_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TDOUBLE)% 2 > 0)?(sizeof(TDOUBLE)/2) + (sizeof(TDOUBLE) % 2):(sizeof(TDOUBLE)/2),
} ;

const TModbusRegisterTableDataDescriptor Double_64bit_ReadWrite_D64RW_registerTable_data_descriptor =
{
	Double_64bit_ReadWrite_D64RW_registerTable_data_descriptor_attribute_byte_sizes,
	Double_64bit_ReadWrite_D64RW_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TDOUBLE)),
	((sizeof(TDOUBLE)% 2 > 0)?(sizeof(TDOUBLE)/2) + (sizeof(TDOUBLE) % 2):(sizeof(TDOUBLE)/2)),
} ;

const TUSIGN16 Action_8bit_WriteOnly_A8WO_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN8),
} ;

const TUSIGN16 Action_8bit_WriteOnly_A8WO_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2),
} ;

const TModbusRegisterTableDataDescriptor Action_8bit_WriteOnly_A8WO_registerTable_data_descriptor =
{
	Action_8bit_WriteOnly_A8WO_registerTable_data_descriptor_attribute_byte_sizes,
	Action_8bit_WriteOnly_A8WO_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN8)),
	((sizeof(TUSIGN8)% 2 > 0)?(sizeof(TUSIGN8)/2) + (sizeof(TUSIGN8) % 2):(sizeof(TUSIGN8)/2)),
} ;

const TUSIGN16 Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN16),
} ;

const TUSIGN16 Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2),
} ;

const TModbusRegisterTableDataDescriptor Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable_data_descriptor =
{
	Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable_data_descriptor_attribute_byte_sizes,
	Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN16)),
	((sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2)),
} ;

const TUSIGN16 Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable_data_descriptor_attribute_byte_sizes[] =
{
	sizeof(TUSIGN16),
} ;

const TUSIGN16 Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable_data_descriptor_attribute_register_sizes[] =
{
	(sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2),
} ;

const TModbusRegisterTableDataDescriptor Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable_data_descriptor =
{
	Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable_data_descriptor_attribute_byte_sizes,
	Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable_data_descriptor_attribute_register_sizes,
	1,
	(sizeof(TUSIGN16)),
	((sizeof(TUSIGN16)% 2 > 0)?(sizeof(TUSIGN16)/2) + (sizeof(TUSIGN16) % 2):(sizeof(TUSIGN16)/2)),
} ;

const TModbusRegisterTable modbusRegisterTables[] =
{
	{
		MODBUS_REGISTER_TABLE_TYPE_COIL,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_READONLY_1BIT_BOOL_B1RO1_START,MODBUS_REGISTER_TABLE_READONLY_1BIT_BOOL_B1RO1_END},
		sizeof(ReadOnly_1bit_Bool_B1RO1_registerTable)/sizeof(TModbusRegisterTableItem),
		ReadOnly_1bit_Bool_B1RO1_registerTable,
		&ReadOnly_1bit_Bool_B1RO1_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_COILS,
		GetTableLinkModbus_Register_Table_Coil_Buffer,
		GetRequestLengthModbus_Register_Table_Coil_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Coil_Buffer,
		FormatToInternalModbus_Register_Table_Coil_Buffer,
		FormatToExternalModbus_Register_Table_Coil_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Coil_Objects,
		AccessObjectsModbus_Register_Table_Coil_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_8BIT_READONLY_DYNAMIC_U8ROD_START,MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_8BIT_READONLY_DYNAMIC_U8ROD_END},
		sizeof(Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable)/sizeof(TModbusRegisterTableItem),
		Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable,
		&Unsigned_Integer_8bit_ReadOnly_dynamic_U8ROD_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_FLOAT_32BIT_READONLY_DYNAMIC_F32ROD_START,MODBUS_REGISTER_TABLE_FLOAT_32BIT_READONLY_DYNAMIC_F32ROD_END},
		sizeof(Float_32bit_ReadOnly_dynamic_F32ROD_registerTable)/sizeof(TModbusRegisterTableItem),
		Float_32bit_ReadOnly_dynamic_F32ROD_registerTable,
		&Float_32bit_ReadOnly_dynamic_F32ROD_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_DOUBLE_64BIT_READONLY_DYNAMIC_D64ROD_START,MODBUS_REGISTER_TABLE_DOUBLE_64BIT_READONLY_DYNAMIC_D64ROD_END},
		sizeof(Double_64bit_ReadOnly_dynamic_D64ROD_registerTable)/sizeof(TModbusRegisterTableItem),
		Double_64bit_ReadOnly_dynamic_D64ROD_registerTable,
		&Double_64bit_ReadOnly_dynamic_D64ROD_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_STRING,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_CHARACTER_8BIT_READONLY_C8RO_START,MODBUS_REGISTER_TABLE_CHARACTER_8BIT_READONLY_C8RO_END},
		sizeof(Character_8bit_ReadOnly_C8RO_registerTable)/sizeof(TModbusRegisterTableItem),
		Character_8bit_ReadOnly_C8RO_registerTable,
		&Character_8bit_ReadOnly_C8RO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_String_Buffer,
		GetRequestLengthModbus_Register_Table_String_Buffer,
		CheckForObjectOverlapModbus_Register_Table_String_Buffer,
		FormatToInternalModbus_Register_Table_String_Buffer,
		FormatToExternalModbus_Register_Table_String_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_String_Objects,
		AccessObjectsModbus_Register_Table_String_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_USIGNED_INTEGER_8BIT_READONLY_U8RO_START,MODBUS_REGISTER_TABLE_USIGNED_INTEGER_8BIT_READONLY_U8RO_END},
		sizeof(Usigned_Integer_8bit_ReadOnly_U8RO_registerTable)/sizeof(TModbusRegisterTableItem),
		Usigned_Integer_8bit_ReadOnly_U8RO_registerTable,
		&Usigned_Integer_8bit_ReadOnly_U8RO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_USIGNED_INTEGER_16BIT_READONLY_U16RO_START,MODBUS_REGISTER_TABLE_USIGNED_INTEGER_16BIT_READONLY_U16RO_END},
		sizeof(Usigned_Integer_16bit_ReadOnly_U16RO_registerTable)/sizeof(TModbusRegisterTableItem),
		Usigned_Integer_16bit_ReadOnly_U16RO_registerTable,
		&Usigned_Integer_16bit_ReadOnly_U16RO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_SIGNED_INTEGER_16BIT_READONLY_S16RO_START,MODBUS_REGISTER_TABLE_SIGNED_INTEGER_16BIT_READONLY_S16RO_END},
		sizeof(Signed_Integer_16bit_ReadOnly_S16RO_registerTable)/sizeof(TModbusRegisterTableItem),
		Signed_Integer_16bit_ReadOnly_S16RO_registerTable,
		&Signed_Integer_16bit_ReadOnly_S16RO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_32BIT_READONLY_U32RO_START,MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_32BIT_READONLY_U32RO_END},
		sizeof(Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable)/sizeof(TModbusRegisterTableItem),
		Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable,
		&Unsigned_Integer_32bit_ReadOnly_U32RO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_FLOAT_32BIT_READONLY_F32RO_START,MODBUS_REGISTER_TABLE_FLOAT_32BIT_READONLY_F32RO_END},
		sizeof(Float_32bit_ReadOnly_F32RO_registerTable)/sizeof(TModbusRegisterTableItem),
		Float_32bit_ReadOnly_F32RO_registerTable,
		&Float_32bit_ReadOnly_F32RO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_VARIANT_16BIT_READONLY_SCANREGISTER1_V16RO1_START,MODBUS_REGISTER_TABLE_VARIANT_16BIT_READONLY_SCANREGISTER1_V16RO1_END},
		sizeof(Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable)/sizeof(TModbusRegisterTableItem),
		Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable,
		&Variant_16bit_ReadOnly_ScanRegister1_V16RO1_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_ONLY,
		{MODBUS_REGISTER_TABLE_VARIANT_16BIT_READONLY_SCANREGISTER2_V16RO2_START,MODBUS_REGISTER_TABLE_VARIANT_16BIT_READONLY_SCANREGISTER2_V16RO2_END},
		sizeof(Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable)/sizeof(TModbusRegisterTableItem),
		Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable,
		&Variant_16bit_ReadOnly_ScanRegister2_V16RO2_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_INPUT_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_STRING,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_CHARACTER_8BIT_READWRITE_C8RW_START,MODBUS_REGISTER_TABLE_CHARACTER_8BIT_READWRITE_C8RW_END},
		sizeof(Character_8bit_ReadWrite_C8RW_registerTable)/sizeof(TModbusRegisterTableItem),
		Character_8bit_ReadWrite_C8RW_registerTable,
		&Character_8bit_ReadWrite_C8RW_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_String_Buffer,
		GetRequestLengthModbus_Register_Table_String_Buffer,
		CheckForObjectOverlapModbus_Register_Table_String_Buffer,
		FormatToInternalModbus_Register_Table_String_Buffer,
		FormatToExternalModbus_Register_Table_String_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_String_Objects,
		AccessObjectsModbus_Register_Table_String_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_8BIT_READWRITE_U8RW_START,MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_8BIT_READWRITE_U8RW_END},
		sizeof(Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable)/sizeof(TModbusRegisterTableItem),
		Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable,
		&Unsigned_Integer_8bit_ReadWrite_U8RW_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_SIGNED_INTEGER_16BIT_READWRITE_S16RW_START,MODBUS_REGISTER_TABLE_SIGNED_INTEGER_16BIT_READWRITE_S16RW_END},
		sizeof(Signed_Integer_16bit_ReadWrite_S16RW_registerTable)/sizeof(TModbusRegisterTableItem),
		Signed_Integer_16bit_ReadWrite_S16RW_registerTable,
		&Signed_Integer_16bit_ReadWrite_S16RW_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_UNSIGNED_INTERGER_32BIT_READWRITE_U32RW_START,MODBUS_REGISTER_TABLE_UNSIGNED_INTERGER_32BIT_READWRITE_U32RW_END},
		sizeof(Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable)/sizeof(TModbusRegisterTableItem),
		Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable,
		&Unsigned_Interger_32bit_ReadWrite_U32RW_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_FLOAT_32BIT_READWRITE_F32RW_START,MODBUS_REGISTER_TABLE_FLOAT_32BIT_READWRITE_F32RW_END},
		sizeof(Float_32bit_ReadWrite_F32RW_registerTable)/sizeof(TModbusRegisterTableItem),
		Float_32bit_ReadWrite_F32RW_registerTable,
		&Float_32bit_ReadWrite_F32RW_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_DOUBLE_64BIT_READWRITE_D64RW_START,MODBUS_REGISTER_TABLE_DOUBLE_64BIT_READWRITE_D64RW_END},
		sizeof(Double_64bit_ReadWrite_D64RW_registerTable)/sizeof(TModbusRegisterTableItem),
		Double_64bit_ReadWrite_D64RW_registerTable,
		&Double_64bit_ReadWrite_D64RW_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_ACTION_8BIT_WRITEONLY_A8WO_START,MODBUS_REGISTER_TABLE_ACTION_8BIT_WRITEONLY_A8WO_END},
		sizeof(Action_8bit_WriteOnly_A8WO_registerTable)/sizeof(TModbusRegisterTableItem),
		Action_8bit_WriteOnly_A8WO_registerTable,
		&Action_8bit_WriteOnly_A8WO_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_16BIT_READWRITE_SCANREGISTER1_U16RW1_START,MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_16BIT_READWRITE_SCANREGISTER1_U16RW1_END},
		sizeof(Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable)/sizeof(TModbusRegisterTableItem),
		Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable,
		&Unsigned_Integer_16bit_ReadWrite_ScanRegister1_U16RW1_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
	{
		MODBUS_REGISTER_TABLE_TYPE_SINGLE,
		MODBUS_REGISTER_TABLE_PRIVILEGE_READ_WRITE,
		{MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_16BIT_READWRITE_SCANREGISTER2_U16RW2_START,MODBUS_REGISTER_TABLE_UNSIGNED_INTEGER_16BIT_READWRITE_SCANREGISTER2_U16RW2_END},
		sizeof(Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable)/sizeof(TModbusRegisterTableItem),
		Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable,
		&Unsigned_Integer_16bit_ReadWrite_ScanRegister2_U16RW2_registerTable_data_descriptor,
		MODBUS_REGISTER_TABLE_LOCATION_HOLDING_REGISTERS,
		GetTableLinkModbus_Register_Table_Single_Buffer,
		GetRequestLengthModbus_Register_Table_Single_Buffer,
		CheckForObjectOverlapModbus_Register_Table_Single_Buffer,
		FormatToInternalModbus_Register_Table_Single_Buffer,
		FormatToExternalModbus_Register_Table_Single_Buffer,
		CheckAccessRightsModbus_Register_Table_Objects,
		CheckRangeModbus_Register_Table_Single_Objects,
		AccessObjectsModbus_Register_Table_Single_Objects,
	},
} ;

//-------------------------------------------------------------------------------------------------
/*!                                                                                                
 \brief   Gets the register table in which a register resides                                     
 \author  GL                                                                                      
 \date    24/07/08                                                                                
 \param   [in] registerIndex - index of the register to get the table id for                      
 \param   [in] modbusRegisterTableLocation - the location (input coils, etc) of the table         
 \return  pModbusRegisterTable - Reference to a register table                                    
 \warning Will return NULL if the register cannot be found                                        
 \test                                                                                            
 date: 2005-08-23                                                                                  
 \n by: GL                                                                                        
 \n environment: IAR Embedded Workbench V3.10A                                                    
 \n intention: 100% code coverage                                                                 
 \n result module test: Pass, 100% code coverage                                                  
 \n result Lint Level 3:                                                                          
 \bug                                                                                             
*/                                                                                                 
//-------------------------------------------------------------------------------------------------
const TModbusRegisterTable *GetRegisterTableModbus_Register_Tables(TUSIGN16 registerIndex,         
                                     TModbusRegisterTableLocation modbusRegisterTableLocation)     
{                                                                                                  
    TBOOL result = eFALSE ;                                                                        
    TUSIGN16 registerTableType ;                                                                   
    const TModbusRegisterTable *pModbusRegisterTable = (const TModbusRegisterTable *)NULL ;        
                                                                                                   
    for (registerTableType = 0 ;                                                                   
                      (registerTableType < MODBUS_REGISTER_TABLE_ID_COUNT) && (result == eFALSE) ; 
                                   registerTableType++)                                            
    {                                                                                              
        // Does this register table reside at the correct location ?                               
        if (modbusRegisterTables[registerTableType].modbusRegisterTableLocation ==                 
                             modbusRegisterTableLocation)                                          
        {                                                                                          
            // Yes, is the register within the table's range ?                                     
            if (registerIndex >= modbusRegisterTables[registerTableType].                          
                                       modbusRegisterTableRange.lowerRange)                        
            {                                                                                      
                if (registerIndex <= modbusRegisterTables[registerTableType].                      
                                       modbusRegisterTableRange.upperRange)                        
                {                                                                                  
                    // Found the table where our register resides                                  
                    result = eTRUE ;                                                               
                    // Set the passed reference to the table index                                 
                    pModbusRegisterTable = &modbusRegisterTables[registerTableType] ;              
                }                                                                                  
           }                                                                                       
        }                                                                                          
    }                                                                                              
    return(pModbusRegisterTable) ;                                                                 
}                                                                                                  
