#ifndef _CONSTRUCTORDEFAULT_H
#define _CONSTRUCTORDEFAULT_H

//LANGUAGE
#define DEFAULT_LANGUAGE        0


//PAGE 1
#define PAGE_1_DEFAULT_FORMAT   10
#define PAGE_1_DEFAULT_LINE_1   18
#define PAGE_1_DEFAULT_LINE_2   1
#define PAGE_1_DEFAULT_LINE_3   0
#define PAGE_1_DEFAULT_LINE_4   17
#define PAGE_1_DEFAULT_LINE_B   0

//PAGE 2
#define PAGE_2_DEFAULT_FORMAT   11
#define PAGE_2_DEFAULT_LINE_1   18
#define PAGE_2_DEFAULT_LINE_2   1
#define PAGE_2_DEFAULT_LINE_3   0
#define PAGE_2_DEFAULT_LINE_4   0
#define PAGE_2_DEFAULT_LINE_B   2

//PAGE 3
#define PAGE_3_DEFAULT_FORMAT   11
#define PAGE_3_DEFAULT_LINE_1   18
#define PAGE_3_DEFAULT_LINE_2   1
#define PAGE_3_DEFAULT_LINE_3   0
#define PAGE_3_DEFAULT_LINE_4   0
#define PAGE_3_DEFAULT_LINE_B   4

//PAGE 4
#define PAGE_4_DEFAULT_FORMAT   11
#define PAGE_4_DEFAULT_LINE_1   18
#define PAGE_4_DEFAULT_LINE_2   1
#define PAGE_4_DEFAULT_LINE_3   0
#define PAGE_4_DEFAULT_LINE_4   0
#define PAGE_4_DEFAULT_LINE_B   0

//PAGE 5
#define PAGE_5_DEFAULT_FORMAT   0
#define PAGE_5_DEFAULT_LINE_1   0
#define PAGE_5_DEFAULT_LINE_2   0
#define PAGE_5_DEFAULT_LINE_3   0
#define PAGE_5_DEFAULT_LINE_4   0
#define PAGE_5_DEFAULT_LINE_B   0

//PAGE 6
#define PAGE_6_DEFAULT_FORMAT   0
#define PAGE_6_DEFAULT_LINE_1   0
#define PAGE_6_DEFAULT_LINE_2   0
#define PAGE_6_DEFAULT_LINE_3   0
#define PAGE_6_DEFAULT_LINE_4   0
#define PAGE_6_DEFAULT_LINE_B   0


//DIAGNOSTICS VIEW
#define DEFAULT_DIAGNOSIS_VIEW   0

#define DEFAULT_AUTOSCROLL_ENABLE eTRUE
#define DEFAULT_LOCAL_OP_ENABLE   eTRUE



//CUSTOM DPs
#define DEFAULT_CUSTOM_DP_1      HMI_2_DP
#define DEFAULT_CUSTOM_DP_2      HMI_2_DP
#define DEFAULT_CUSTOM_DP_3      HMI_2_DP
#define DEFAULT_CUSTOM_DP_4      HMI_2_DP
#define DEFAULT_CUSTOM_DP_5      HMI_2_DP
#define DEFAULT_CUSTOM_DP_6      HMI_0_DP
#define DEFAULT_CUSTOM_DP_7      HMI_0_DP
#define DEFAULT_CUSTOM_DP_8      HMI_0_DP
#define DEFAULT_CUSTOM_DP_9      HMI_0_DP
#define DEFAULT_CUSTOM_DP_10      HMI_0_DP
#define DEFAULT_CUSTOM_DP_11      HMI_0_DP


#endif
