#ifndef _FIXEDICONDEF_H
#define _FIXEDICONDEF_H

#pragma diag_suppress=Pm025

typedef enum
{
/*
 --------------------------- IMPORTANT --------------------------------------------
 The elements in "animatedIconTable[][]", "smallIconTable[][]" (in lcd_patterns. h)
 and this enum definition are all related and any change in one must be reflected
 in the others. All are used in the MSP430 low level driver so no changes should
 be made without consideration of this.
 ----------------------------------------------------------------------------------
*/
    // Monochrome Animation Icons
    ICON_PART_BLANK,
        FIRST_MONO_ANIMATION = ICON_PART_BLANK,
    ICON_PART_DIAL_T1,
    ICON_PART_DIAL_T2,
    ICON_PART_DIAL_C1,
    ICON_PART_DIAL_C2,
    ICON_PART_DIAL_B,
    ICON_PART_SCRWDRV_C1,
    ICON_PART_SCRWDRV_C2,
    ICON_PART_SCRWDRV_B1,
    ICON_PART_SCRWDRV_B2,
    ICON_PART_DEVICE_T,
    ICON_PART_DEVICE_B,
    ICON_PART_DEV_CLR_DISP,
    ICON_PART_DEV_BLK_DISP,
    ICON_PART_BELLOWS_C1,
    ICON_PART_BELLOWS_C2,
    ICON_PART_BELLOWS_C3,
    ICON_PART_BELLOWS_B1,
    ICON_PART_BELLOWS_B2,
    ICON_PART_BELLOWS_B3,
    ICON_PART_COMMS_C1,
    ICON_PART_COMMS_C2,
    ICON_PART_DISPLAY_T,
    ICON_PART_DISPLAY_NEG,
    ICON_PART_DISPLAY_POS,
    ICON_PART_DISPLAY_B,
    ICON_PART_MAGNIFY_T,
    ICON_PART_MAGNIFY_B,
    ICON_PART_MAGNIFY_C1,
    ICON_PART_MAGNIFY_C2,
        LAST_MONO_ANIMATION = ICON_PART_MAGNIFY_C2,

    // Small Icons
    ICON_NUMBER_EDIT,
        FIRST_SMALL_ICON = ICON_NUMBER_EDIT,
    ICON_STRING_EDIT,
    ICON_ENUM_EDIT,
    ICON_ADJUST_EDIT1,
    ICON_ADJUST_EDIT2,
    ICON_NEXT_OPERATOR_FRAME,
    ICON_MENU,
    ICON_WARNING_TRIANGLE,
    ICON_INFORMATION,
    ICON_ALARM_BELL,
    ICON_PREV_FRAME,
    ICON_LOCK,
    ICON_CLOCK,
    ICON_SCROLL_ARROWS,
    ICON_KEY,
    ICON_HOURGLASS,
    ICON_NEMUR_NONE,
    ICON_NEMUR_CHECKFUNCTION,
    ICON_NEMUR_OFFSPEC,
    ICON_NEMUR_MAINTENANCEREQD,
    ICON_NEMUR_FAILURE,
    ICON_NEMUR_INFORMATIONONLY,
    ICON_ARM_LOGOUT,
    ICON_ARM_READONLY_LEVEL,
    ICON_ARM_STANDARD_LEVEL,
    ICON_ARM_ADVANCED_LEVEL,
    ICON_ARM_SERVICE_LEVEL,
        LAST_SMALL_ICON = ICON_ARM_SERVICE_LEVEL,

    // Colour Animation Icons
    ICON_PART_DEVICE_COLOUR_1,
        FIRST_COLOUR_ANIMATION = ICON_PART_DEVICE_COLOUR_1,
    ICON_PART_DEVICE_COLOUR_2,
    ICON_PART_DEVICE_COLOUR_3,
    ICON_PART_DEVICE_COLOUR_4,
    ICON_PART_DEVICE_COLOUR_5,
    ICON_PART_DEVICE_COLOUR_6,
    ICON_PART_DISPLAY_COLOUR_1,
    ICON_PART_DISPLAY_COLOUR_2,
    ICON_PART_IO_COLOUR_1,
    ICON_PART_IO_COLOUR_2,
    ICON_PART_IO_COLOUR_3,
    ICON_PART_IO_COLOUR_4,
    ICON_PART_IO_COLOUR_5,
    ICON_PART_IO_COLOUR_6,
    ICON_PART_CONTROL_COLOUR_1,
    ICON_PART_CONTROL_COLOUR_2,
    ICON_PART_CONTROL_COLOUR_3,
    ICON_PART_CONTROL_COLOUR_4,
    ICON_PART_CONTROL_COLOUR_5,
    ICON_PART_CONTROL_COLOUR_6,
    ICON_PART_ALARM_COLOUR_1,
    ICON_PART_ALARM_COLOUR_2,
    ICON_PART_ALARM_COLOUR_3,
    ICON_PART_ALARM_COLOUR_4,
    ICON_PART_ALARM_COLOUR_5,
    ICON_PART_ALARM_COLOUR_6,
    ICON_PART_PROFILE_COLOUR_1,
    ICON_PART_PROFILE_COLOUR_2,
    ICON_PART_PROFILE_COLOUR_3,
    ICON_PART_PROFILE_COLOUR_4,
    ICON_PART_PROFILE_COLOUR_5,
    ICON_PART_PROFILE_COLOUR_6,
    ICON_PART_TOTALIZER_COLOUR_1,
    ICON_PART_TOTALIZER_COLOUR_2,
    ICON_PART_TOTALIZER_COLOUR_3,
    ICON_PART_TOTALIZER_COLOUR_4,
    ICON_PART_TOTALIZER_COLOUR_5,
    ICON_PART_TOTALIZER_COLOUR_6,
    ICON_PART_FUNCTIONS_COLOUR_1,
    ICON_PART_FUNCTIONS_COLOUR_2,
    ICON_PART_COMMS_COLOUR_1,
    ICON_PART_COMMS_COLOUR_2,
    ICON_PART_COMMS_COLOUR_3,
    ICON_PART_COMMS_COLOUR_4,
    ICON_PART_DIAGNOSTICS_COLOUR_1,
    ICON_PART_DIAGNOSTICS_COLOUR_2,
    ICON_PART_SERVICE_COLOUR_1,
    ICON_PART_SERVICE_COLOUR_2,
    ICON_PART_SERVICE_COLOUR_3,
    ICON_PART_SERVICE_COLOUR_4,
    ICON_PART_DEVICE_INFO_COLOUR_1,
    ICON_PART_DEVICE_INFO_COLOUR_2,
    ICON_PART_BASIC_SETUP_COLOUR_1,
    ICON_PART_BASIC_SETUP_COLOUR_2,
    ICON_PART_BASIC_SETUP_COLOUR_3,
    ICON_PART_CALIBRATE_COLOUR_1,
    ICON_PART_CALIBRATE_COLOUR_2,
    ICON_PART_SENSOR_SETUP_COLOUR_1,
    ICON_PART_SENSOR_SETUP_COLOUR_2,
    ICON_PART_SENSOR_SETUP_COLOUR_3,
    ICON_PART_SENSOR_SETUP_COLOUR_4,
//    ICON_PART_SENSOR_SETUP_COLOUR_5,
//    ICON_PART_SENSOR_SETUP_COLOUR_6,
    ICON_PART_MEDIACARD_COLOUR_1,
    ICON_PART_MEDIACARD_COLOUR_2,
    ICON_PART_MEDIACARD_COLOUR_3,
    ICON_PART_MEDIACARD_COLOUR_4,
        LAST_COLOUR_ANIMATION = ICON_PART_MEDIACARD_COLOUR_4

/*
 --------------------------- IMPORTANT --------------------------------------------
 The elements in "animatedIconTable[][]", "smallIconTable[][]" (in lcd_patterns. h)
 and this enum definition are all related and any change in one must be reflected
 in the others. All are used in the MSP430 low level driver so no changes should
 be made without consideration of this.
 ----------------------------------------------------------------------------------
*/

}ICON_PART_TYPE;


#pragma diag_default=Pm025

#endif
