// IncludeList_Frames_2.h

//+@ HMIGen IncludeList_Frames_2 @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "nvInitIndeces.h"
#include "Frames.h"
#include "menus.h"
#include "Enums.h"
#include "configIcons.h"
#include "stringTable.h"
#include "characterSet.h"
#include "unitsTable.h"

//-@ HMIGen IncludeList_Frames_2 @-

