// IncludeList_Frames_1.h

//+@ HMIGen IncludeList_Frames_1 @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "StringDefinitions.h"
#include "validityTest.h"
#include "specialOperation.h"

//-@ HMIGen IncludeList_Frames_1 @-

