// IncludeList_Layer2.h

//+@ HMIGen IncludeList_LowLevelLayer2 @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "HART/Layer2/Interface/layer2.h"

//-@ HMIGen IncludeList_LowLevelLayer2 @-

