// IncludeList_WriteProtect.h

//+@ HMIGen IncludeList_WriteProtect @+

// If the files generated by HMIGen are not saved to the ....HMI\Source\  folder then
// the relative file path to the include files below must be added to the lines below.

#include "WriteAccessAllowed.h"

//-@ HMIGen IncludeList_WriteProtect @-

