#ifndef _KEYSTATEDEFINITIONS_H
#define _KEYSTATEDEFINITIONS_H

#define	KEYSTATE_NONE				0x00	// no key pressed
#define	KEYSTATE_RIGHT				0x01	// rh soft key pressed
#define	KEYSTATE_LEFT				0x02	// lh soft key pressed
#define	KEYSTATE_UP					0x04	// up key pressed
#define	KEYSTATE_DOWN				0x08	// down key pressed
#define KEYSTATE_UP_AND_DOWN        0x0C    // up and down keys pressed
#define	KEYSTATE_DEFAULT_CONTRAST	0x03	// rh & lh keys pressed
#define	KEYSTATE_EXIT_CONFIGURATION	0x80	// not strictly a key state - this key state is issued by configuration mode manager
#define KEYSTATE_AUTOSCROLL         0x40    // not strictly a key state - this key state is issued by ProcessAutoscroll()

typedef	enum
{
	 COMMAND_DO_NOT_MOVE
	,COMMAND_MENU
    ,COMMAND_STANDARD_LEVEL
    ,COMMAND_ADVANCED_LEVEL
    ,COMMAND_SERVICE_LEVEL
	,COMMAND_LAUNCH_OPERATOR_MENU
	,COMMAND_RELAUNCH_OPERATOR_MENU

	,COMMAND_CHECK_SECURITY_PASSWORD
	,COMMAND_RETURN_TO_OPERATOR_PAGE
    ,COMMAND_LAUNCH_QUICK_ADJUST_FRAME

	,COMMAND_EXIT
	,COMMAND_NEXT_OPERATOR_FRAME
	,COMMAND_AUTO_NEXT_OPERATOR_FRAME
	,COMMAND_MOVE_UP_LEVEL
	,COMMAND_MOVE_DOWN_LEVEL
	,COMMAND_SELECT_CONFIG_LEVEL
	,COMMAND_BACK
	,COMMAND_EDIT
	,COMMAND_MOVE_CURSOR
	,COMMAND_MOVE_CURSOR_TO_END
	,COMMAND_OK
    ,COMMAND_OK_MANUAL_CAL
	,COMMAND_CANCEL
	,COMMAND_OK_CANCEL
	,COMMAND_OK_CANCEL_2PT_PH
	,COMMAND_EXIT_ADJUST_OK
	,COMMAND_EXIT_ADJUST_CANCEL

	,COMMAND_EXIT_ADJUST_OK_AND_BACK
	,COMMAND_EXIT_ADJUST_OK_AND_NEXT_EASYSETUP
	,COMMAND_NEXT_EASYSETUP
	,COMMAND_EXIT_ADJUST_CANCEL_AND_BACK
	,COMMAND_EXIT_ADJUST_CANCEL_AND_NEXT_EASYSETUP

	,COMMAND_NEXT_SEQUENCE
	,COMMAND_EXIT_ADJUST_OK_AND_NEXT_SEQUENCE
	,COMMAND_EXIT_ADJUST_CANCEL_AND_NEXT_SEQUENCE

	,COMMAND_MOVE_UP_MENU
	,COMMAND_MOVE_DOWN_MENU
	,COMMAND_SELECT_FROM_MENU
	,COMMAND_ADJUST_UP
	,COMMAND_ADJUST_DOWN
	,COMMAND_DEFAULT_CONTRAST
	,COMMAND_DO_AUTO_ADJUST

    ,COMMAND_BACK_MOVE_UP_SELECT
    ,COMMAND_BACK_MOVE_DOWN_SELECT

}MOVE_COMMAND_TYPE;
#endif
