
#ifdef HMI_SUPPORTS_WAVEFORM_FRAMES

#define CRV_EDIT_MAX_CHARS  6



#define V_SCALE_FIELD_WIDTH 17
#define V_SCALE_FIELD_X_POS 0
#define COL_0_X_POS         3

#define WAVEFORM_PLOT_AREA_SIZE 25

#define WAVEFORM_FRAME_COL_0    0
#define WAVEFORM_FRAME_COL_1    1
#define WAVEFORM_FRAME_COL_2    2
#define WAVEFORM_FRAME_COL_3    3
#define WAVEFORM_FRAME_COL_4    4
#define WAVEFORM_FRAME_LAST_COL WAVEFORM_FRAME_COL_4

#define WAVEFORM_FRAME_ROW_0    0
#define WAVEFORM_FRAME_ROW_1    1
#define WAVEFORM_FRAME_ROW_2    2
#define WAVEFORM_FRAME_ROW_3    3
#define WAVEFORM_FRAME_ROW_4    4
#define WAVEFORM_FRAME_ROW_5    5

// Line 0 constants
//-----------------
#define PRV_ID_XPOS                     1
#define PRV_ID_JUSTIFICATION            JUSTIFY_LEFT_WITH_INDENT_1_PIXEL
#define PRV_JUSTIFICATION               JUSTIFY_LEFT_WITH_INDENT_20_PIXEL

#define CRV_ID_XPOS                     79
#define CRV_ID_JUSTIFICATION            JUSTIFY_LEFT_WITH_INDENT_79_PIXEL
#define CRV_JUSTIFICATION               JUSTIFY_LEFT_WITH_INDENT_98_PIXEL

// Line 7 constants
//-----------------
#define UNITS_1_FIELD_WIDTH             12
#define UNITS_2_FIELD_WIDTH             18

#define OFFSET_VALUE_FIELD_XPOS         18
#define OFFSET_VALUE_FIELD_WIDTH        17
#define OFFSET_UNITS_FIELD_XPOS         (OFFSET_VALUE_FIELD_XPOS + OFFSET_VALUE_FIELD_WIDTH)
#define OFFSET_UNITS_FIELD_WIDTH        UNITS_1_FIELD_WIDTH

#define H_WIDTH_VALUE_FIELD_XPOS        71
#define H_WIDTH_VALUE_FIELD_WIDTH       17
#define H_WIDTH_UNITS1_FIELD_XPOS       (H_WIDTH_VALUE_FIELD_XPOS + H_WIDTH_VALUE_FIELD_WIDTH)
#define H_WIDTH_UNITS1_FIELD_WIDTH      UNITS_1_FIELD_WIDTH
#define H_WIDTH_UNITS2_FIELD_XPOS       (H_WIDTH_UNITS1_FIELD_XPOS + H_WIDTH_UNITS1_FIELD_WIDTH)
#define H_WIDTH_UNITS2_FIELD_WIDTH      UNITS_2_FIELD_WIDTH

#endif //#ifdef HMI_SUPPORTS_WAVEFORM_FRAMES
